provider: auth0
major-version: 3
esc:
    enabled: true
env:
    AUTH0_CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID }}
    AUTH0_CLIENT_SECRET: ${{ secrets.AUTH0_CLIENT_SECRET }}
    AUTH0_DOMAIN: ${{ secrets.AUTH0_DOMAIN }}
makeTemplate: bridged
team: ecosystem
pulumiConvert: 1
registryDocs: true
plugins:
    - name: terraform
      version: "1.0.16"
      kind: converter
integrationTestProvider: true
