// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System.Collections.Immutable;

namespace Pulumi.Auth0
{
    public static class Config
    {
        private static readonly Pulumi.Config __config = new Pulumi.Config("auth0");
        public static string? ClientId { get; set; } = __config.Get("clientId") ?? Utilities.GetEnv("AUTH0_CLIENT_ID");

        public static string? ClientSecret { get; set; } = __config.Get("clientSecret") ?? Utilities.GetEnv("AUTH0_CLIENT_SECRET");

        public static bool? Debug { get; set; } = __config.GetBoolean("debug") ?? Utilities.GetEnvBoolean("AUTH0_DEBUG");

        public static string? Domain { get; set; } = __config.Get("domain") ?? Utilities.GetEnv("AUTH0_DOMAIN");

    }
}
