# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs

__all__ = [
    'GetOrganizationRoleGroupsResult',
    'AwaitableGetOrganizationRoleGroupsResult',
    'get_organization_role_groups',
    'get_organization_role_groups_output',
]

@pulumi.output_type
class GetOrganizationRoleGroupsResult:
    """
    A collection of values returned by getOrganizationRoleGroups.
    """
    def __init__(__self__, groups=None, id=None, organization_id=None, role_id=None):
        if groups and not isinstance(groups, list):
            raise TypeError("Expected argument 'groups' to be a list")
        pulumi.set(__self__, "groups", groups)
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if organization_id and not isinstance(organization_id, str):
            raise TypeError("Expected argument 'organization_id' to be a str")
        pulumi.set(__self__, "organization_id", organization_id)
        if role_id and not isinstance(role_id, str):
            raise TypeError("Expected argument 'role_id' to be a str")
        pulumi.set(__self__, "role_id", role_id)

    @_builtins.property
    @pulumi.getter
    def groups(self) -> Sequence['outputs.GetOrganizationRoleGroupsGroupResult']:
        """
        The groups assigned to the role.
        """
        return pulumi.get(self, "groups")

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str:
        """
        The provider-assigned unique ID for this managed resource.
        """
        return pulumi.get(self, "id")

    @_builtins.property
    @pulumi.getter(name="organizationId")
    def organization_id(self) -> _builtins.str:
        """
        The ID of the organization.
        """
        return pulumi.get(self, "organization_id")

    @_builtins.property
    @pulumi.getter(name="roleId")
    def role_id(self) -> _builtins.str:
        """
        The ID of the role to retrieve the assigned groups for.
        """
        return pulumi.get(self, "role_id")


class AwaitableGetOrganizationRoleGroupsResult(GetOrganizationRoleGroupsResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetOrganizationRoleGroupsResult(
            groups=self.groups,
            id=self.id,
            organization_id=self.organization_id,
            role_id=self.role_id)


def get_organization_role_groups(organization_id: Optional[_builtins.str] = None,
                                 role_id: Optional[_builtins.str] = None,
                                 opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetOrganizationRoleGroupsResult:
    """
    Data source to retrieve the groups assigned to a specific role within the context of an organization. For the members with a direct role assignment, use `get_organization_role_members`. (EA only)

    ## Example Usage

    ```python
    import pulumi
    import pulumi_auth0 as auth0

    # The groups assigned to an organization-level role.
    my_role_groups = auth0.get_organization_role_groups(organization_id="org_abcdefghkijklmn",
        role_id="rol_abcdefghkijklmn")
    ```


    :param _builtins.str organization_id: The ID of the organization.
    :param _builtins.str role_id: The ID of the role to retrieve the assigned groups for.
    """
    __args__ = dict()
    __args__['organizationId'] = organization_id
    __args__['roleId'] = role_id
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('auth0:index/getOrganizationRoleGroups:getOrganizationRoleGroups', __args__, opts=opts, typ=GetOrganizationRoleGroupsResult).value

    return AwaitableGetOrganizationRoleGroupsResult(
        groups=pulumi.get(__ret__, 'groups'),
        id=pulumi.get(__ret__, 'id'),
        organization_id=pulumi.get(__ret__, 'organization_id'),
        role_id=pulumi.get(__ret__, 'role_id'))
def get_organization_role_groups_output(organization_id: pulumi.Input[Optional[_builtins.str]] = None,
                                        role_id: pulumi.Input[Optional[_builtins.str]] = None,
                                        opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetOrganizationRoleGroupsResult]:
    """
    Data source to retrieve the groups assigned to a specific role within the context of an organization. For the members with a direct role assignment, use `get_organization_role_members`. (EA only)

    ## Example Usage

    ```python
    import pulumi
    import pulumi_auth0 as auth0

    # The groups assigned to an organization-level role.
    my_role_groups = auth0.get_organization_role_groups(organization_id="org_abcdefghkijklmn",
        role_id="rol_abcdefghkijklmn")
    ```


    :param _builtins.str organization_id: The ID of the organization.
    :param _builtins.str role_id: The ID of the role to retrieve the assigned groups for.
    """
    __args__ = dict()
    __args__['organizationId'] = organization_id
    __args__['roleId'] = role_id
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('auth0:index/getOrganizationRoleGroups:getOrganizationRoleGroups', __args__, opts=opts, typ=GetOrganizationRoleGroupsResult)
    return __ret__.apply(lambda __response__: GetOrganizationRoleGroupsResult(
        groups=pulumi.get(__response__, 'groups'),
        id=pulumi.get(__response__, 'id'),
        organization_id=pulumi.get(__response__, 'organization_id'),
        role_id=pulumi.get(__response__, 'role_id')))
