// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package auth0

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi-auth0/sdk/v3/go/auth0/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// With this resource, you can configure directory provisioning (directory sync) for `Google Workspace` Enterprise connections. This enables automatic user provisioning from the identity provider to Auth0.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi-auth0/sdk/v3/go/auth0"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			googleWorkspace, err := auth0.NewConnection(ctx, "google_workspace", &auth0.ConnectionArgs{
//				Name:        pulumi.String("google-workspace-connection"),
//				DisplayName: pulumi.String("Google Workspace"),
//				Strategy:    pulumi.String("google-apps"),
//				Options: &auth0.ConnectionOptionsArgs{
//					ClientId:       pulumi.String("your-google-client-id"),
//					ClientSecret:   pulumi.String("your-google-client-secret"),
//					Domain:         pulumi.String("example.com"),
//					ApiEnableUsers: pulumi.Bool(true),
//				},
//			})
//			if err != nil {
//				return err
//			}
//			// Configure directory provisioning with default settings
//			_, err = auth0.NewConnectionDirectory(ctx, "default", &auth0.ConnectionDirectoryArgs{
//				ConnectionId: googleWorkspace.ID(),
//			})
//			if err != nil {
//				return err
//			}
//			// Configure directory provisioning with custom mapping and auto-sync enabled
//			_, err = auth0.NewConnectionDirectory(ctx, "custom", &auth0.ConnectionDirectoryArgs{
//				ConnectionId:             googleWorkspace.ID(),
//				SynchronizeAutomatically: pulumi.Bool(true),
//				Mappings: auth0.ConnectionDirectoryMappingArray{
//					&auth0.ConnectionDirectoryMappingArgs{
//						Auth0: pulumi.String("email"),
//						Idp:   pulumi.String("primaryEmail"),
//					},
//					&auth0.ConnectionDirectoryMappingArgs{
//						Auth0: pulumi.String("family_name"),
//						Idp:   pulumi.String("name.familyName"),
//					},
//					&auth0.ConnectionDirectoryMappingArgs{
//						Auth0: pulumi.String("given_name"),
//						Idp:   pulumi.String("name.givenName"),
//					},
//					&auth0.ConnectionDirectoryMappingArgs{
//						Auth0: pulumi.String("external_id"),
//						Idp:   pulumi.String("id"),
//					},
//				},
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
//
// ## Import
//
// ```sh
// $ pulumi import auth0:index/connectionDirectory:ConnectionDirectory custom "con_XXXXXXXXXXXXXX"
// ```
type ConnectionDirectory struct {
	pulumi.CustomResourceState

	// ID of the connection for this directory provisioning configuration.
	ConnectionId pulumi.StringOutput `pulumi:"connectionId"`
	// Name of the connection for this directory provisioning configuration.
	ConnectionName pulumi.StringOutput `pulumi:"connectionName"`
	// The timestamp at which the directory provisioning configuration was created.
	CreatedAt pulumi.StringOutput `pulumi:"createdAt"`
	// The timestamp at which the connection was last synchronized.
	LastSynchronizationAt pulumi.StringOutput `pulumi:"lastSynchronizationAt"`
	// The error message of the last synchronization, if any.
	LastSynchronizationError pulumi.StringOutput `pulumi:"lastSynchronizationError"`
	// The status of the last synchronization.
	LastSynchronizationStatus pulumi.StringOutput `pulumi:"lastSynchronizationStatus"`
	// Mapping between Auth0 attributes and IDP user attributes. Defaults to default mapping for the connection type if not specified.
	Mappings ConnectionDirectoryMappingArrayOutput `pulumi:"mappings"`
	// Strategy of the connection for this directory provisioning configuration.
	Strategy pulumi.StringOutput `pulumi:"strategy"`
	// Whether periodic automatic synchronization is enabled. Defaults to false.
	SynchronizeAutomatically pulumi.BoolOutput `pulumi:"synchronizeAutomatically"`
	// The timestamp at which the directory provisioning configuration was last updated.
	UpdatedAt pulumi.StringOutput `pulumi:"updatedAt"`
}

// NewConnectionDirectory registers a new resource with the given unique name, arguments, and options.
func NewConnectionDirectory(ctx *pulumi.Context,
	name string, args *ConnectionDirectoryArgs, opts ...pulumi.ResourceOption) (*ConnectionDirectory, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.ConnectionId == nil {
		return nil, errors.New("invalid value for required argument 'ConnectionId'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource ConnectionDirectory
	err := ctx.RegisterResource("auth0:index/connectionDirectory:ConnectionDirectory", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetConnectionDirectory gets an existing ConnectionDirectory resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetConnectionDirectory(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *ConnectionDirectoryState, opts ...pulumi.ResourceOption) (*ConnectionDirectory, error) {
	var resource ConnectionDirectory
	err := ctx.ReadResource("auth0:index/connectionDirectory:ConnectionDirectory", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering ConnectionDirectory resources.
type connectionDirectoryState struct {
	// ID of the connection for this directory provisioning configuration.
	ConnectionId *string `pulumi:"connectionId"`
	// Name of the connection for this directory provisioning configuration.
	ConnectionName *string `pulumi:"connectionName"`
	// The timestamp at which the directory provisioning configuration was created.
	CreatedAt *string `pulumi:"createdAt"`
	// The timestamp at which the connection was last synchronized.
	LastSynchronizationAt *string `pulumi:"lastSynchronizationAt"`
	// The error message of the last synchronization, if any.
	LastSynchronizationError *string `pulumi:"lastSynchronizationError"`
	// The status of the last synchronization.
	LastSynchronizationStatus *string `pulumi:"lastSynchronizationStatus"`
	// Mapping between Auth0 attributes and IDP user attributes. Defaults to default mapping for the connection type if not specified.
	Mappings []ConnectionDirectoryMapping `pulumi:"mappings"`
	// Strategy of the connection for this directory provisioning configuration.
	Strategy *string `pulumi:"strategy"`
	// Whether periodic automatic synchronization is enabled. Defaults to false.
	SynchronizeAutomatically *bool `pulumi:"synchronizeAutomatically"`
	// The timestamp at which the directory provisioning configuration was last updated.
	UpdatedAt *string `pulumi:"updatedAt"`
}

type ConnectionDirectoryState struct {
	// ID of the connection for this directory provisioning configuration.
	ConnectionId pulumi.StringPtrInput
	// Name of the connection for this directory provisioning configuration.
	ConnectionName pulumi.StringPtrInput
	// The timestamp at which the directory provisioning configuration was created.
	CreatedAt pulumi.StringPtrInput
	// The timestamp at which the connection was last synchronized.
	LastSynchronizationAt pulumi.StringPtrInput
	// The error message of the last synchronization, if any.
	LastSynchronizationError pulumi.StringPtrInput
	// The status of the last synchronization.
	LastSynchronizationStatus pulumi.StringPtrInput
	// Mapping between Auth0 attributes and IDP user attributes. Defaults to default mapping for the connection type if not specified.
	Mappings ConnectionDirectoryMappingArrayInput
	// Strategy of the connection for this directory provisioning configuration.
	Strategy pulumi.StringPtrInput
	// Whether periodic automatic synchronization is enabled. Defaults to false.
	SynchronizeAutomatically pulumi.BoolPtrInput
	// The timestamp at which the directory provisioning configuration was last updated.
	UpdatedAt pulumi.StringPtrInput
}

func (ConnectionDirectoryState) ElementType() reflect.Type {
	return reflect.TypeOf((*connectionDirectoryState)(nil)).Elem()
}

type connectionDirectoryArgs struct {
	// ID of the connection for this directory provisioning configuration.
	ConnectionId string `pulumi:"connectionId"`
	// Mapping between Auth0 attributes and IDP user attributes. Defaults to default mapping for the connection type if not specified.
	Mappings []ConnectionDirectoryMapping `pulumi:"mappings"`
	// Whether periodic automatic synchronization is enabled. Defaults to false.
	SynchronizeAutomatically *bool `pulumi:"synchronizeAutomatically"`
}

// The set of arguments for constructing a ConnectionDirectory resource.
type ConnectionDirectoryArgs struct {
	// ID of the connection for this directory provisioning configuration.
	ConnectionId pulumi.StringInput
	// Mapping between Auth0 attributes and IDP user attributes. Defaults to default mapping for the connection type if not specified.
	Mappings ConnectionDirectoryMappingArrayInput
	// Whether periodic automatic synchronization is enabled. Defaults to false.
	SynchronizeAutomatically pulumi.BoolPtrInput
}

func (ConnectionDirectoryArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*connectionDirectoryArgs)(nil)).Elem()
}

type ConnectionDirectoryInput interface {
	pulumi.Input

	ToConnectionDirectoryOutput() ConnectionDirectoryOutput
	ToConnectionDirectoryOutputWithContext(ctx context.Context) ConnectionDirectoryOutput
}

func (*ConnectionDirectory) ElementType() reflect.Type {
	return reflect.TypeOf((**ConnectionDirectory)(nil)).Elem()
}

func (i *ConnectionDirectory) ToConnectionDirectoryOutput() ConnectionDirectoryOutput {
	return i.ToConnectionDirectoryOutputWithContext(context.Background())
}

func (i *ConnectionDirectory) ToConnectionDirectoryOutputWithContext(ctx context.Context) ConnectionDirectoryOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ConnectionDirectoryOutput)
}

// ConnectionDirectoryArrayInput is an input type that accepts ConnectionDirectoryArray and ConnectionDirectoryArrayOutput values.
// You can construct a concrete instance of `ConnectionDirectoryArrayInput` via:
//
//	ConnectionDirectoryArray{ ConnectionDirectoryArgs{...} }
type ConnectionDirectoryArrayInput interface {
	pulumi.Input

	ToConnectionDirectoryArrayOutput() ConnectionDirectoryArrayOutput
	ToConnectionDirectoryArrayOutputWithContext(context.Context) ConnectionDirectoryArrayOutput
}

type ConnectionDirectoryArray []ConnectionDirectoryInput

func (ConnectionDirectoryArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*ConnectionDirectory)(nil)).Elem()
}

func (i ConnectionDirectoryArray) ToConnectionDirectoryArrayOutput() ConnectionDirectoryArrayOutput {
	return i.ToConnectionDirectoryArrayOutputWithContext(context.Background())
}

func (i ConnectionDirectoryArray) ToConnectionDirectoryArrayOutputWithContext(ctx context.Context) ConnectionDirectoryArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ConnectionDirectoryArrayOutput)
}

// ConnectionDirectoryMapInput is an input type that accepts ConnectionDirectoryMap and ConnectionDirectoryMapOutput values.
// You can construct a concrete instance of `ConnectionDirectoryMapInput` via:
//
//	ConnectionDirectoryMap{ "key": ConnectionDirectoryArgs{...} }
type ConnectionDirectoryMapInput interface {
	pulumi.Input

	ToConnectionDirectoryMapOutput() ConnectionDirectoryMapOutput
	ToConnectionDirectoryMapOutputWithContext(context.Context) ConnectionDirectoryMapOutput
}

type ConnectionDirectoryMap map[string]ConnectionDirectoryInput

func (ConnectionDirectoryMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*ConnectionDirectory)(nil)).Elem()
}

func (i ConnectionDirectoryMap) ToConnectionDirectoryMapOutput() ConnectionDirectoryMapOutput {
	return i.ToConnectionDirectoryMapOutputWithContext(context.Background())
}

func (i ConnectionDirectoryMap) ToConnectionDirectoryMapOutputWithContext(ctx context.Context) ConnectionDirectoryMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ConnectionDirectoryMapOutput)
}

type ConnectionDirectoryOutput struct{ *pulumi.OutputState }

func (ConnectionDirectoryOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**ConnectionDirectory)(nil)).Elem()
}

func (o ConnectionDirectoryOutput) ToConnectionDirectoryOutput() ConnectionDirectoryOutput {
	return o
}

func (o ConnectionDirectoryOutput) ToConnectionDirectoryOutputWithContext(ctx context.Context) ConnectionDirectoryOutput {
	return o
}

// ID of the connection for this directory provisioning configuration.
func (o ConnectionDirectoryOutput) ConnectionId() pulumi.StringOutput {
	return o.ApplyT(func(v *ConnectionDirectory) pulumi.StringOutput { return v.ConnectionId }).(pulumi.StringOutput)
}

// Name of the connection for this directory provisioning configuration.
func (o ConnectionDirectoryOutput) ConnectionName() pulumi.StringOutput {
	return o.ApplyT(func(v *ConnectionDirectory) pulumi.StringOutput { return v.ConnectionName }).(pulumi.StringOutput)
}

// The timestamp at which the directory provisioning configuration was created.
func (o ConnectionDirectoryOutput) CreatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v *ConnectionDirectory) pulumi.StringOutput { return v.CreatedAt }).(pulumi.StringOutput)
}

// The timestamp at which the connection was last synchronized.
func (o ConnectionDirectoryOutput) LastSynchronizationAt() pulumi.StringOutput {
	return o.ApplyT(func(v *ConnectionDirectory) pulumi.StringOutput { return v.LastSynchronizationAt }).(pulumi.StringOutput)
}

// The error message of the last synchronization, if any.
func (o ConnectionDirectoryOutput) LastSynchronizationError() pulumi.StringOutput {
	return o.ApplyT(func(v *ConnectionDirectory) pulumi.StringOutput { return v.LastSynchronizationError }).(pulumi.StringOutput)
}

// The status of the last synchronization.
func (o ConnectionDirectoryOutput) LastSynchronizationStatus() pulumi.StringOutput {
	return o.ApplyT(func(v *ConnectionDirectory) pulumi.StringOutput { return v.LastSynchronizationStatus }).(pulumi.StringOutput)
}

// Mapping between Auth0 attributes and IDP user attributes. Defaults to default mapping for the connection type if not specified.
func (o ConnectionDirectoryOutput) Mappings() ConnectionDirectoryMappingArrayOutput {
	return o.ApplyT(func(v *ConnectionDirectory) ConnectionDirectoryMappingArrayOutput { return v.Mappings }).(ConnectionDirectoryMappingArrayOutput)
}

// Strategy of the connection for this directory provisioning configuration.
func (o ConnectionDirectoryOutput) Strategy() pulumi.StringOutput {
	return o.ApplyT(func(v *ConnectionDirectory) pulumi.StringOutput { return v.Strategy }).(pulumi.StringOutput)
}

// Whether periodic automatic synchronization is enabled. Defaults to false.
func (o ConnectionDirectoryOutput) SynchronizeAutomatically() pulumi.BoolOutput {
	return o.ApplyT(func(v *ConnectionDirectory) pulumi.BoolOutput { return v.SynchronizeAutomatically }).(pulumi.BoolOutput)
}

// The timestamp at which the directory provisioning configuration was last updated.
func (o ConnectionDirectoryOutput) UpdatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v *ConnectionDirectory) pulumi.StringOutput { return v.UpdatedAt }).(pulumi.StringOutput)
}

type ConnectionDirectoryArrayOutput struct{ *pulumi.OutputState }

func (ConnectionDirectoryArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*ConnectionDirectory)(nil)).Elem()
}

func (o ConnectionDirectoryArrayOutput) ToConnectionDirectoryArrayOutput() ConnectionDirectoryArrayOutput {
	return o
}

func (o ConnectionDirectoryArrayOutput) ToConnectionDirectoryArrayOutputWithContext(ctx context.Context) ConnectionDirectoryArrayOutput {
	return o
}

func (o ConnectionDirectoryArrayOutput) Index(i pulumi.IntInput) ConnectionDirectoryOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *ConnectionDirectory {
		return vs[0].([]*ConnectionDirectory)[vs[1].(int)]
	}).(ConnectionDirectoryOutput)
}

type ConnectionDirectoryMapOutput struct{ *pulumi.OutputState }

func (ConnectionDirectoryMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*ConnectionDirectory)(nil)).Elem()
}

func (o ConnectionDirectoryMapOutput) ToConnectionDirectoryMapOutput() ConnectionDirectoryMapOutput {
	return o
}

func (o ConnectionDirectoryMapOutput) ToConnectionDirectoryMapOutputWithContext(ctx context.Context) ConnectionDirectoryMapOutput {
	return o
}

func (o ConnectionDirectoryMapOutput) MapIndex(k pulumi.StringInput) ConnectionDirectoryOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *ConnectionDirectory {
		return vs[0].(map[string]*ConnectionDirectory)[vs[1].(string)]
	}).(ConnectionDirectoryOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*ConnectionDirectoryInput)(nil)).Elem(), &ConnectionDirectory{})
	pulumi.RegisterInputType(reflect.TypeOf((*ConnectionDirectoryArrayInput)(nil)).Elem(), ConnectionDirectoryArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*ConnectionDirectoryMapInput)(nil)).Elem(), ConnectionDirectoryMap{})
	pulumi.RegisterOutputType(ConnectionDirectoryOutput{})
	pulumi.RegisterOutputType(ConnectionDirectoryArrayOutput{})
	pulumi.RegisterOutputType(ConnectionDirectoryMapOutput{})
}
