// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Auth0.Outputs
{

    [OutputType]
    public sealed class ClientB2bIntegrationConfiguration
    {
        /// <summary>
        /// The type of integration used to connect to this B2B integration client. One of custom*auth*server, third_party, application
        /// </summary>
        public readonly string? IntegrationType;
        /// <summary>
        /// ID of the self-service SSO profile (an `auth0.SelfServiceProfile` id, in `ssp_...` format) linked to this B2B integration client. Maximum 1.
        /// </summary>
        public readonly string? SsoProfiles;

        [OutputConstructor]
        private ClientB2bIntegrationConfiguration(
            string? integrationType,

            string? ssoProfiles)
        {
            IntegrationType = integrationType;
            SsoProfiles = ssoProfiles;
        }
    }
}
