// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Auth0.Outputs
{

    [OutputType]
    public sealed class EmailCredentials
    {
        /// <summary>
        /// AWS Access Key ID. Used only for AWS.
        /// </summary>
        public readonly string? AccessKeyId;
        /// <summary>
        /// API Key for your email service. Will always be encrypted in our database.
        /// </summary>
        public readonly string? ApiKey;
        /// <summary>
        /// API User for your email service. This field is not accepted by the API any more so it will be removed in a future major version.
        /// </summary>
        public readonly string? ApiUser;
        /// <summary>
        /// Domain name.
        /// </summary>
        public readonly string? Domain;
        /// <summary>
        /// Default region. Used only for AWS, Mailgun, and SparkPost.
        /// </summary>
        public readonly string? Region;
        /// <summary>
        /// AWS Secret Key. Will always be encrypted in our database. Used only for AWS.
        /// </summary>
        public readonly string? SecretAccessKey;
        /// <summary>
        /// Hostname or IP address of your SMTP server. Used only for SMTP.
        /// </summary>
        public readonly string? SmtpHost;
        /// <summary>
        /// SMTP password. Used only for SMTP.
        /// </summary>
        public readonly string? SmtpPass;
        /// <summary>
        /// Port used by your SMTP server. Please avoid using port 25 if possible because many providers have limitations on this port. Used only for SMTP.
        /// </summary>
        public readonly int? SmtpPort;
        /// <summary>
        /// SMTP username. Used only for SMTP.
        /// </summary>
        public readonly string? SmtpUser;

        [OutputConstructor]
        private EmailCredentials(
            string? accessKeyId,

            string? apiKey,

            string? apiUser,

            string? domain,

            string? region,

            string? secretAccessKey,

            string? smtpHost,

            string? smtpPass,

            int? smtpPort,

            string? smtpUser)
        {
            AccessKeyId = accessKeyId;
            ApiKey = apiKey;
            ApiUser = apiUser;
            Domain = domain;
            Region = region;
            SecretAccessKey = secretAccessKey;
            SmtpHost = smtpHost;
            SmtpPass = smtpPass;
            SmtpPort = smtpPort;
            SmtpUser = smtpUser;
        }
    }
}
