// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Auth0.Outputs
{

    [OutputType]
    public sealed class GetClientsClientOidcLogoutResult
    {
        /// <summary>
        /// Configure OIDC logout initiators for the Client
        /// </summary>
        public readonly ImmutableArray<Outputs.GetClientsClientOidcLogoutBackchannelLogoutInitiatorResult> BackchannelLogoutInitiators;
        /// <summary>
        /// Set of URLs that are valid to call back from Auth0 for OIDC backchannel logout. Currently only one URL is allowed.
        /// </summary>
        public readonly ImmutableArray<string> BackchannelLogoutUrls;

        [OutputConstructor]
        private GetClientsClientOidcLogoutResult(
            ImmutableArray<Outputs.GetClientsClientOidcLogoutBackchannelLogoutInitiatorResult> backchannelLogoutInitiators,

            ImmutableArray<string> backchannelLogoutUrls)
        {
            BackchannelLogoutInitiators = backchannelLogoutInitiators;
            BackchannelLogoutUrls = backchannelLogoutUrls;
        }
    }
}
