// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Auth0.Outputs
{

    [OutputType]
    public sealed class SelfServiceProfileBranding
    {
        /// <summary>
        /// Configuration settings for colors for branding.
        /// </summary>
        public readonly Outputs.SelfServiceProfileBrandingColors? Colors;
        /// <summary>
        /// URL of logo to display on login page.
        /// </summary>
        public readonly string? LogoUrl;

        [OutputConstructor]
        private SelfServiceProfileBranding(
            Outputs.SelfServiceProfileBrandingColors? colors,

            string? logoUrl)
        {
            Colors = colors;
            LogoUrl = logoUrl;
        }
    }
}
