// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.auth0;

import com.pulumi.auth0.ActionArgs;
import com.pulumi.auth0.Utilities;
import com.pulumi.auth0.inputs.ActionState;
import com.pulumi.auth0.outputs.ActionDependency;
import com.pulumi.auth0.outputs.ActionModule;
import com.pulumi.auth0.outputs.ActionSecret;
import com.pulumi.auth0.outputs.ActionSupportedTriggers;
import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import java.lang.Boolean;
import java.lang.String;
import java.util.List;
import java.util.Optional;
import javax.annotation.Nullable;

/**
 * Actions are secure, tenant-specific, versioned functions written in Node.js that execute at certain points during the Auth0 runtime. Actions are used to customize and extend Auth0&#39;s capabilities with custom logic.
 * 
 * &gt; An action bound to a trigger cannot be deleted. To destroy such an action, the trigger binding must first be deleted.
 * A binding is usually managed by auth0.TriggerAction resource.
 * The provider also supports a 1:many variant auth0_trigger_actions.
 * If by any means, a binding is missing is the state file, it can be imported to the state and deleted, before attempting to delete the action.
 * 
 * &gt; Values provided in the sensitive values shall be stored in the raw state as plain text: secrets.
 * Read more about sensitive data in state.
 * 
 * ## Example Usage
 * 
 * <pre>
 * {@code
 * package generated_program;
 * 
 * import com.pulumi.Context;
 * import com.pulumi.Pulumi;
 * import com.pulumi.core.Output;
 * import com.pulumi.auth0.Action;
 * import com.pulumi.auth0.ActionArgs;
 * import com.pulumi.auth0.inputs.ActionSupportedTriggersArgs;
 * import com.pulumi.auth0.inputs.ActionDependencyArgs;
 * import com.pulumi.auth0.inputs.ActionSecretArgs;
 * import com.pulumi.std.StdFunctions;
 * import java.util.List;
 * import java.util.ArrayList;
 * import java.util.Map;
 * import java.io.File;
 * import java.nio.file.Files;
 * import java.nio.file.Paths;
 * 
 * public class App }{{@code
 *     public static void main(String[] args) }{{@code
 *         Pulumi.run(App::stack);
 *     }}{@code
 * 
 *     public static void stack(Context ctx) }{{@code
 *         var myAction = new Action("myAction", ActionArgs.builder()
 *             .name(StdFunctions.format(Map.ofEntries(
 *                 Map.entry("input", "Test Action %s"),
 *                 Map.entry("args", StdFunctions.timestamp(Map.ofEntries(
 *                 )).result())
 *             )).result())
 *             .runtime("node22")
 *             .deploy(true)
 *             .code("""
 * /**
 *  * Handler that will be called during the execution of a PostLogin flow.
 *  *
 *  * }{@literal @}{@code param }{{@code Event}}{@code  event - Details about the user and the context in which they are logging in.
 *  * }{@literal @}{@code param }{{@code PostLoginAPI}}{@code  api - Interface whose methods can be used to change the behavior of the login.
 *  *}&#47;{@code
 *  exports.onExecutePostLogin = async (event, api) => }{{@code
 *    console.log(event);
 *  }}{@code ;
 *             """)
 *             .supportedTriggers(ActionSupportedTriggersArgs.builder()
 *                 .id("post-login")
 *                 .version("v3")
 *                 .build())
 *             .dependencies(            
 *                 ActionDependencyArgs.builder()
 *                     .name("lodash")
 *                     .version("latest")
 *                     .build(),
 *                 ActionDependencyArgs.builder()
 *                     .name("request")
 *                     .version("latest")
 *                     .build())
 *             .secrets(            
 *                 ActionSecretArgs.builder()
 *                     .name("FOO")
 *                     .value("Foo")
 *                     .build(),
 *                 ActionSecretArgs.builder()
 *                     .name("BAR")
 *                     .value("Bar")
 *                     .build())
 *             .build());
 * 
 *     }}{@code
 * }}{@code
 * }
 * </pre>
 * 
 * ## Import
 * 
 * This resource can be imported by specifying the action ID.
 * 
 * Example:
 * 
 * ```sh
 * $ pulumi import auth0:index/action:Action my_action &#34;12f4f21b-017a-319d-92e7-2291c1ca36c4&#34;
 * ```
 * 
 * &gt; For security reasons importing `secrets` is not allowed. Therefore, it is advised to import
 * the action without secrets and adding them back after the action has been imported.
 * 
 */
@ResourceType(type="auth0:index/action:Action")
public class Action extends com.pulumi.resources.CustomResource {
    /**
     * The source code of the action.
     * 
     */
    @Export(name="code", refs={String.class}, tree="[0]")
    private Output<String> code;

    /**
     * @return The source code of the action.
     * 
     */
    public Output<String> code() {
        return this.code;
    }
    /**
     * List of third party npm modules, and their versions, that this action depends on.
     * 
     */
    @Export(name="dependencies", refs={List.class,ActionDependency.class}, tree="[0,1]")
    private Output</* @Nullable */ List<ActionDependency>> dependencies;

    /**
     * @return List of third party npm modules, and their versions, that this action depends on.
     * 
     */
    public Output<Optional<List<ActionDependency>>> dependencies() {
        return Codegen.optional(this.dependencies);
    }
    /**
     * Deploying an action will create a new immutable version of the action. If the action is currently bound to a trigger, then the system will begin executing the newly deployed version of the action immediately.
     * 
     */
    @Export(name="deploy", refs={Boolean.class}, tree="[0]")
    private Output</* @Nullable */ Boolean> deploy;

    /**
     * @return Deploying an action will create a new immutable version of the action. If the action is currently bound to a trigger, then the system will begin executing the newly deployed version of the action immediately.
     * 
     */
    public Output<Optional<Boolean>> deploy() {
        return Codegen.optional(this.deploy);
    }
    /**
     * List of action modules and their versions that this action depends on.
     * 
     */
    @Export(name="modules", refs={List.class,ActionModule.class}, tree="[0,1]")
    private Output</* @Nullable */ List<ActionModule>> modules;

    /**
     * @return List of action modules and their versions that this action depends on.
     * 
     */
    public Output<Optional<List<ActionModule>>> modules() {
        return Codegen.optional(this.modules);
    }
    /**
     * The name of the action.
     * 
     */
    @Export(name="name", refs={String.class}, tree="[0]")
    private Output<String> name;

    /**
     * @return The name of the action.
     * 
     */
    public Output<String> name() {
        return this.name;
    }
    /**
     * The Node runtime. Possible values are: `node12`, `node16` (not recommended), `node18`, `node22`
     * 
     */
    @Export(name="runtime", refs={String.class}, tree="[0]")
    private Output<String> runtime;

    /**
     * @return The Node runtime. Possible values are: `node12`, `node16` (not recommended), `node18`, `node22`
     * 
     */
    public Output<String> runtime() {
        return this.runtime;
    }
    /**
     * List of secrets that are included in an action or a version of an action. Partial management of secrets is not supported. If the secret block is edited, the whole object is re-provisioned.
     * 
     */
    @Export(name="secrets", refs={List.class,ActionSecret.class}, tree="[0,1]")
    private Output</* @Nullable */ List<ActionSecret>> secrets;

    /**
     * @return List of secrets that are included in an action or a version of an action. Partial management of secrets is not supported. If the secret block is edited, the whole object is re-provisioned.
     * 
     */
    public Output<Optional<List<ActionSecret>>> secrets() {
        return Codegen.optional(this.secrets);
    }
    /**
     * List of triggers that this action supports. At this time, an action can only target a single trigger at a time. Read Retrieving the set of triggers available within actions to retrieve the latest trigger versions supported.
     * 
     */
    @Export(name="supportedTriggers", refs={ActionSupportedTriggers.class}, tree="[0]")
    private Output<ActionSupportedTriggers> supportedTriggers;

    /**
     * @return List of triggers that this action supports. At this time, an action can only target a single trigger at a time. Read Retrieving the set of triggers available within actions to retrieve the latest trigger versions supported.
     * 
     */
    public Output<ActionSupportedTriggers> supportedTriggers() {
        return this.supportedTriggers;
    }
    /**
     * Version ID of the action. This value is available if `deploy` is set to true.
     * 
     */
    @Export(name="versionId", refs={String.class}, tree="[0]")
    private Output<String> versionId;

    /**
     * @return Version ID of the action. This value is available if `deploy` is set to true.
     * 
     */
    public Output<String> versionId() {
        return this.versionId;
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public Action(java.lang.String name) {
        this(name, ActionArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public Action(java.lang.String name, ActionArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public Action(java.lang.String name, ActionArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("auth0:index/action:Action", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), false);
    }

    private Action(java.lang.String name, Output<java.lang.String> id, @Nullable ActionState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("auth0:index/action:Action", name, state, makeResourceOptions(options, id), false);
    }

    private static ActionArgs makeArgs(ActionArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? ActionArgs.Empty : args;
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static Action get(java.lang.String name, Output<java.lang.String> id, @Nullable ActionState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new Action(name, id, state, options);
    }
}
