// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.auth0;

import com.pulumi.auth0.inputs.LogStreamSinkArgs;
import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Boolean;
import java.lang.String;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class LogStreamArgs extends com.pulumi.resources.ResourceArgs {

    public static final LogStreamArgs Empty = new LogStreamArgs();

    /**
     * Only logs events matching these filters will be delivered by the stream. If omitted or empty, all events will be delivered. Filters available: `auth.ancillary.fail`, `auth.ancillary.success`, `auth.login.fail`, `auth.login.notification`, `auth.login.success`, `auth.logout.fail`, `auth.logout.success`, `auth.signup.fail`, `auth.signup.success`, `auth.silent_auth.fail`, `auth.silent_auth.success`, `auth.token_exchange.fail`, `auth.token_exchange.success`, `management.fail`, `management.success`, `system.notification`, `user.fail`, `user.notification`, `user.success`, `other`.
     * 
     */
    @Import(name="filters")
    private @Nullable Output<List<Map<String,String>>> filters;

    /**
     * @return Only logs events matching these filters will be delivered by the stream. If omitted or empty, all events will be delivered. Filters available: `auth.ancillary.fail`, `auth.ancillary.success`, `auth.login.fail`, `auth.login.notification`, `auth.login.success`, `auth.logout.fail`, `auth.logout.success`, `auth.signup.fail`, `auth.signup.success`, `auth.silent_auth.fail`, `auth.silent_auth.success`, `auth.token_exchange.fail`, `auth.token_exchange.success`, `management.fail`, `management.success`, `system.notification`, `user.fail`, `user.notification`, `user.success`, `other`.
     * 
     */
    public Optional<Output<List<Map<String,String>>>> filters() {
        return Optional.ofNullable(this.filters);
    }

    /**
     * Set True for priority log streams, False for non-priority
     * 
     */
    @Import(name="isPriority")
    private @Nullable Output<Boolean> isPriority;

    /**
     * @return Set True for priority log streams, False for non-priority
     * 
     */
    public Optional<Output<Boolean>> isPriority() {
        return Optional.ofNullable(this.isPriority);
    }

    /**
     * Name of the log stream.
     * 
     */
    @Import(name="name")
    private @Nullable Output<String> name;

    /**
     * @return Name of the log stream.
     * 
     */
    public Optional<Output<String>> name() {
        return Optional.ofNullable(this.name);
    }

    /**
     * The sink configuration for the log stream.
     * 
     */
    @Import(name="sink", required=true)
    private Output<LogStreamSinkArgs> sink;

    /**
     * @return The sink configuration for the log stream.
     * 
     */
    public Output<LogStreamSinkArgs> sink() {
        return this.sink;
    }

    /**
     * The current status of the log stream. Options are &#34;active&#34;, &#34;paused&#34;, &#34;suspended&#34;.
     * 
     */
    @Import(name="status")
    private @Nullable Output<String> status;

    /**
     * @return The current status of the log stream. Options are &#34;active&#34;, &#34;paused&#34;, &#34;suspended&#34;.
     * 
     */
    public Optional<Output<String>> status() {
        return Optional.ofNullable(this.status);
    }

    /**
     * Type of the log stream, which indicates the sink provider. Options include: `eventbridge`, `eventgrid`, `http`, `datadog`, `splunk`, `sumo`, `mixpanel`, `segment`.
     * 
     */
    @Import(name="type", required=true)
    private Output<String> type;

    /**
     * @return Type of the log stream, which indicates the sink provider. Options include: `eventbridge`, `eventgrid`, `http`, `datadog`, `splunk`, `sumo`, `mixpanel`, `segment`.
     * 
     */
    public Output<String> type() {
        return this.type;
    }

    private LogStreamArgs() {}

    private LogStreamArgs(LogStreamArgs $) {
        this.filters = $.filters;
        this.isPriority = $.isPriority;
        this.name = $.name;
        this.sink = $.sink;
        this.status = $.status;
        this.type = $.type;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(LogStreamArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private LogStreamArgs $;

        public Builder() {
            $ = new LogStreamArgs();
        }

        public Builder(LogStreamArgs defaults) {
            $ = new LogStreamArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param filters Only logs events matching these filters will be delivered by the stream. If omitted or empty, all events will be delivered. Filters available: `auth.ancillary.fail`, `auth.ancillary.success`, `auth.login.fail`, `auth.login.notification`, `auth.login.success`, `auth.logout.fail`, `auth.logout.success`, `auth.signup.fail`, `auth.signup.success`, `auth.silent_auth.fail`, `auth.silent_auth.success`, `auth.token_exchange.fail`, `auth.token_exchange.success`, `management.fail`, `management.success`, `system.notification`, `user.fail`, `user.notification`, `user.success`, `other`.
         * 
         * @return builder
         * 
         */
        public Builder filters(@Nullable Output<List<Map<String,String>>> filters) {
            $.filters = filters;
            return this;
        }

        /**
         * @param filters Only logs events matching these filters will be delivered by the stream. If omitted or empty, all events will be delivered. Filters available: `auth.ancillary.fail`, `auth.ancillary.success`, `auth.login.fail`, `auth.login.notification`, `auth.login.success`, `auth.logout.fail`, `auth.logout.success`, `auth.signup.fail`, `auth.signup.success`, `auth.silent_auth.fail`, `auth.silent_auth.success`, `auth.token_exchange.fail`, `auth.token_exchange.success`, `management.fail`, `management.success`, `system.notification`, `user.fail`, `user.notification`, `user.success`, `other`.
         * 
         * @return builder
         * 
         */
        public Builder filters(List<Map<String,String>> filters) {
            return filters(Output.of(filters));
        }

        /**
         * @param filters Only logs events matching these filters will be delivered by the stream. If omitted or empty, all events will be delivered. Filters available: `auth.ancillary.fail`, `auth.ancillary.success`, `auth.login.fail`, `auth.login.notification`, `auth.login.success`, `auth.logout.fail`, `auth.logout.success`, `auth.signup.fail`, `auth.signup.success`, `auth.silent_auth.fail`, `auth.silent_auth.success`, `auth.token_exchange.fail`, `auth.token_exchange.success`, `management.fail`, `management.success`, `system.notification`, `user.fail`, `user.notification`, `user.success`, `other`.
         * 
         * @return builder
         * 
         */
        public Builder filters(Map<String,String>... filters) {
            return filters(List.of(filters));
        }

        /**
         * @param isPriority Set True for priority log streams, False for non-priority
         * 
         * @return builder
         * 
         */
        public Builder isPriority(@Nullable Output<Boolean> isPriority) {
            $.isPriority = isPriority;
            return this;
        }

        /**
         * @param isPriority Set True for priority log streams, False for non-priority
         * 
         * @return builder
         * 
         */
        public Builder isPriority(Boolean isPriority) {
            return isPriority(Output.of(isPriority));
        }

        /**
         * @param name Name of the log stream.
         * 
         * @return builder
         * 
         */
        public Builder name(@Nullable Output<String> name) {
            $.name = name;
            return this;
        }

        /**
         * @param name Name of the log stream.
         * 
         * @return builder
         * 
         */
        public Builder name(String name) {
            return name(Output.of(name));
        }

        /**
         * @param sink The sink configuration for the log stream.
         * 
         * @return builder
         * 
         */
        public Builder sink(Output<LogStreamSinkArgs> sink) {
            $.sink = sink;
            return this;
        }

        /**
         * @param sink The sink configuration for the log stream.
         * 
         * @return builder
         * 
         */
        public Builder sink(LogStreamSinkArgs sink) {
            return sink(Output.of(sink));
        }

        /**
         * @param status The current status of the log stream. Options are &#34;active&#34;, &#34;paused&#34;, &#34;suspended&#34;.
         * 
         * @return builder
         * 
         */
        public Builder status(@Nullable Output<String> status) {
            $.status = status;
            return this;
        }

        /**
         * @param status The current status of the log stream. Options are &#34;active&#34;, &#34;paused&#34;, &#34;suspended&#34;.
         * 
         * @return builder
         * 
         */
        public Builder status(String status) {
            return status(Output.of(status));
        }

        /**
         * @param type Type of the log stream, which indicates the sink provider. Options include: `eventbridge`, `eventgrid`, `http`, `datadog`, `splunk`, `sumo`, `mixpanel`, `segment`.
         * 
         * @return builder
         * 
         */
        public Builder type(Output<String> type) {
            $.type = type;
            return this;
        }

        /**
         * @param type Type of the log stream, which indicates the sink provider. Options include: `eventbridge`, `eventgrid`, `http`, `datadog`, `splunk`, `sumo`, `mixpanel`, `segment`.
         * 
         * @return builder
         * 
         */
        public Builder type(String type) {
            return type(Output.of(type));
        }

        public LogStreamArgs build() {
            if ($.sink == null) {
                throw new MissingRequiredPropertyException("LogStreamArgs", "sink");
            }
            if ($.type == null) {
                throw new MissingRequiredPropertyException("LogStreamArgs", "type");
            }
            return $;
        }
    }

}
