// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.auth0;

import com.pulumi.auth0.inputs.SelfServiceProfileBrandingArgs;
import com.pulumi.auth0.inputs.SelfServiceProfileUserAttributeArgs;
import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class SelfServiceProfileArgs extends com.pulumi.resources.ResourceArgs {

    public static final SelfServiceProfileArgs Empty = new SelfServiceProfileArgs();

    /**
     * List of IdP strategies that will be shown to users during the Self-Service SSO flow. Valid values are: oidc, samlp, waad, google-apps, adfs, okta, keycloak-samlp, pingfederate, auth0-samlp, okta-samlp.
     * 
     */
    @Import(name="allowedStrategies")
    private @Nullable Output<List<String>> allowedStrategies;

    /**
     * @return List of IdP strategies that will be shown to users during the Self-Service SSO flow. Valid values are: oidc, samlp, waad, google-apps, adfs, okta, keycloak-samlp, pingfederate, auth0-samlp, okta-samlp.
     * 
     */
    public Optional<Output<List<String>>> allowedStrategies() {
        return Optional.ofNullable(this.allowedStrategies);
    }

    /**
     * Field can be used to customize the look and feel of the wizard.
     * 
     */
    @Import(name="branding")
    private @Nullable Output<SelfServiceProfileBrandingArgs> branding;

    /**
     * @return Field can be used to customize the look and feel of the wizard.
     * 
     */
    public Optional<Output<SelfServiceProfileBrandingArgs>> branding() {
        return Optional.ofNullable(this.branding);
    }

    /**
     * The description of the self-service Profile
     * 
     */
    @Import(name="description")
    private @Nullable Output<String> description;

    /**
     * @return The description of the self-service Profile
     * 
     */
    public Optional<Output<String>> description() {
        return Optional.ofNullable(this.description);
    }

    /**
     * The name of the self-service Profile
     * 
     */
    @Import(name="name")
    private @Nullable Output<String> name;

    /**
     * @return The name of the self-service Profile
     * 
     */
    public Optional<Output<String>> name() {
        return Optional.ofNullable(this.name);
    }

    /**
     * The ID of the user attribute profile to use for this self-service profile. Cannot be used with user_attributes.
     * 
     */
    @Import(name="userAttributeProfileId")
    private @Nullable Output<String> userAttributeProfileId;

    /**
     * @return The ID of the user attribute profile to use for this self-service profile. Cannot be used with user_attributes.
     * 
     */
    public Optional<Output<String>> userAttributeProfileId() {
        return Optional.ofNullable(this.userAttributeProfileId);
    }

    /**
     * This array stores the mapping information that will be shown to the user during the SS-SSO flow. The user will be prompted to map the attributes on their identity provider to ensure the specified attributes get passed to Auth0. Cannot be used with user*attribute*profile*id.
     * 
     */
    @Import(name="userAttributes")
    private @Nullable Output<List<SelfServiceProfileUserAttributeArgs>> userAttributes;

    /**
     * @return This array stores the mapping information that will be shown to the user during the SS-SSO flow. The user will be prompted to map the attributes on their identity provider to ensure the specified attributes get passed to Auth0. Cannot be used with user*attribute*profile*id.
     * 
     */
    public Optional<Output<List<SelfServiceProfileUserAttributeArgs>>> userAttributes() {
        return Optional.ofNullable(this.userAttributes);
    }

    private SelfServiceProfileArgs() {}

    private SelfServiceProfileArgs(SelfServiceProfileArgs $) {
        this.allowedStrategies = $.allowedStrategies;
        this.branding = $.branding;
        this.description = $.description;
        this.name = $.name;
        this.userAttributeProfileId = $.userAttributeProfileId;
        this.userAttributes = $.userAttributes;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(SelfServiceProfileArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private SelfServiceProfileArgs $;

        public Builder() {
            $ = new SelfServiceProfileArgs();
        }

        public Builder(SelfServiceProfileArgs defaults) {
            $ = new SelfServiceProfileArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param allowedStrategies List of IdP strategies that will be shown to users during the Self-Service SSO flow. Valid values are: oidc, samlp, waad, google-apps, adfs, okta, keycloak-samlp, pingfederate, auth0-samlp, okta-samlp.
         * 
         * @return builder
         * 
         */
        public Builder allowedStrategies(@Nullable Output<List<String>> allowedStrategies) {
            $.allowedStrategies = allowedStrategies;
            return this;
        }

        /**
         * @param allowedStrategies List of IdP strategies that will be shown to users during the Self-Service SSO flow. Valid values are: oidc, samlp, waad, google-apps, adfs, okta, keycloak-samlp, pingfederate, auth0-samlp, okta-samlp.
         * 
         * @return builder
         * 
         */
        public Builder allowedStrategies(List<String> allowedStrategies) {
            return allowedStrategies(Output.of(allowedStrategies));
        }

        /**
         * @param allowedStrategies List of IdP strategies that will be shown to users during the Self-Service SSO flow. Valid values are: oidc, samlp, waad, google-apps, adfs, okta, keycloak-samlp, pingfederate, auth0-samlp, okta-samlp.
         * 
         * @return builder
         * 
         */
        public Builder allowedStrategies(String... allowedStrategies) {
            return allowedStrategies(List.of(allowedStrategies));
        }

        /**
         * @param branding Field can be used to customize the look and feel of the wizard.
         * 
         * @return builder
         * 
         */
        public Builder branding(@Nullable Output<SelfServiceProfileBrandingArgs> branding) {
            $.branding = branding;
            return this;
        }

        /**
         * @param branding Field can be used to customize the look and feel of the wizard.
         * 
         * @return builder
         * 
         */
        public Builder branding(SelfServiceProfileBrandingArgs branding) {
            return branding(Output.of(branding));
        }

        /**
         * @param description The description of the self-service Profile
         * 
         * @return builder
         * 
         */
        public Builder description(@Nullable Output<String> description) {
            $.description = description;
            return this;
        }

        /**
         * @param description The description of the self-service Profile
         * 
         * @return builder
         * 
         */
        public Builder description(String description) {
            return description(Output.of(description));
        }

        /**
         * @param name The name of the self-service Profile
         * 
         * @return builder
         * 
         */
        public Builder name(@Nullable Output<String> name) {
            $.name = name;
            return this;
        }

        /**
         * @param name The name of the self-service Profile
         * 
         * @return builder
         * 
         */
        public Builder name(String name) {
            return name(Output.of(name));
        }

        /**
         * @param userAttributeProfileId The ID of the user attribute profile to use for this self-service profile. Cannot be used with user_attributes.
         * 
         * @return builder
         * 
         */
        public Builder userAttributeProfileId(@Nullable Output<String> userAttributeProfileId) {
            $.userAttributeProfileId = userAttributeProfileId;
            return this;
        }

        /**
         * @param userAttributeProfileId The ID of the user attribute profile to use for this self-service profile. Cannot be used with user_attributes.
         * 
         * @return builder
         * 
         */
        public Builder userAttributeProfileId(String userAttributeProfileId) {
            return userAttributeProfileId(Output.of(userAttributeProfileId));
        }

        /**
         * @param userAttributes This array stores the mapping information that will be shown to the user during the SS-SSO flow. The user will be prompted to map the attributes on their identity provider to ensure the specified attributes get passed to Auth0. Cannot be used with user*attribute*profile*id.
         * 
         * @return builder
         * 
         */
        public Builder userAttributes(@Nullable Output<List<SelfServiceProfileUserAttributeArgs>> userAttributes) {
            $.userAttributes = userAttributes;
            return this;
        }

        /**
         * @param userAttributes This array stores the mapping information that will be shown to the user during the SS-SSO flow. The user will be prompted to map the attributes on their identity provider to ensure the specified attributes get passed to Auth0. Cannot be used with user*attribute*profile*id.
         * 
         * @return builder
         * 
         */
        public Builder userAttributes(List<SelfServiceProfileUserAttributeArgs> userAttributes) {
            return userAttributes(Output.of(userAttributes));
        }

        /**
         * @param userAttributes This array stores the mapping information that will be shown to the user during the SS-SSO flow. The user will be prompted to map the attributes on their identity provider to ensure the specified attributes get passed to Auth0. Cannot be used with user*attribute*profile*id.
         * 
         * @return builder
         * 
         */
        public Builder userAttributes(SelfServiceProfileUserAttributeArgs... userAttributes) {
            return userAttributes(List.of(userAttributes));
        }

        public SelfServiceProfileArgs build() {
            return $;
        }
    }

}
