// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.auth0.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class BrandingFontArgs extends com.pulumi.resources.ResourceArgs {

    public static final BrandingFontArgs Empty = new BrandingFontArgs();

    /**
     * String. URL for the custom font.
     * 
     */
    @Import(name="url")
    private @Nullable Output<String> url;

    /**
     * @return String. URL for the custom font.
     * 
     */
    public Optional<Output<String>> url() {
        return Optional.ofNullable(this.url);
    }

    private BrandingFontArgs() {}

    private BrandingFontArgs(BrandingFontArgs $) {
        this.url = $.url;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(BrandingFontArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private BrandingFontArgs $;

        public Builder() {
            $ = new BrandingFontArgs();
        }

        public Builder(BrandingFontArgs defaults) {
            $ = new BrandingFontArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param url String. URL for the custom font.
         * 
         * @return builder
         * 
         */
        public Builder url(@Nullable Output<String> url) {
            $.url = url;
            return this;
        }

        /**
         * @param url String. URL for the custom font.
         * 
         * @return builder
         * 
         */
        public Builder url(String url) {
            return url(Output.of(url));
        }

        public BrandingFontArgs build() {
            return $;
        }
    }

}
