// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.auth0.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class ClientMyOrganizationConfigurationThirdPartyClientAccessArgs extends com.pulumi.resources.ResourceArgs {

    public static final ClientMyOrganizationConfigurationThirdPartyClientAccessArgs Empty = new ClientMyOrganizationConfigurationThirdPartyClientAccessArgs();

    /**
     * The third-party client access values that can be set on organizations created for this client through the My Organization API. Required whenever this block is set — the API rejects the block without it. Possible values: `allow`, `block`. Unlike `auth0.ConnectionProfile`&#39;s `crossAppAccessResourceApp`, a single value is accepted here. (EA Only)
     * 
     */
    @Import(name="allowedValues", required=true)
    private Output<List<String>> allowedValues;

    /**
     * @return The third-party client access values that can be set on organizations created for this client through the My Organization API. Required whenever this block is set — the API rejects the block without it. Possible values: `allow`, `block`. Unlike `auth0.ConnectionProfile`&#39;s `crossAppAccessResourceApp`, a single value is accepted here. (EA Only)
     * 
     */
    public Output<List<String>> allowedValues() {
        return this.allowedValues;
    }

    /**
     * The default third-party client access value applied to organizations created for this client. The API currently only accepts &#34;block&#34;; &#34;allow&#34; is rejected with a 400 error, so this is exposed as computed-only rather than user-settable. (EA Only)
     * 
     */
    @Import(name="defaultValue")
    private @Nullable Output<String> defaultValue;

    /**
     * @return The default third-party client access value applied to organizations created for this client. The API currently only accepts &#34;block&#34;; &#34;allow&#34; is rejected with a 400 error, so this is exposed as computed-only rather than user-settable. (EA Only)
     * 
     */
    public Optional<Output<String>> defaultValue() {
        return Optional.ofNullable(this.defaultValue);
    }

    private ClientMyOrganizationConfigurationThirdPartyClientAccessArgs() {}

    private ClientMyOrganizationConfigurationThirdPartyClientAccessArgs(ClientMyOrganizationConfigurationThirdPartyClientAccessArgs $) {
        this.allowedValues = $.allowedValues;
        this.defaultValue = $.defaultValue;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(ClientMyOrganizationConfigurationThirdPartyClientAccessArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private ClientMyOrganizationConfigurationThirdPartyClientAccessArgs $;

        public Builder() {
            $ = new ClientMyOrganizationConfigurationThirdPartyClientAccessArgs();
        }

        public Builder(ClientMyOrganizationConfigurationThirdPartyClientAccessArgs defaults) {
            $ = new ClientMyOrganizationConfigurationThirdPartyClientAccessArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param allowedValues The third-party client access values that can be set on organizations created for this client through the My Organization API. Required whenever this block is set — the API rejects the block without it. Possible values: `allow`, `block`. Unlike `auth0.ConnectionProfile`&#39;s `crossAppAccessResourceApp`, a single value is accepted here. (EA Only)
         * 
         * @return builder
         * 
         */
        public Builder allowedValues(Output<List<String>> allowedValues) {
            $.allowedValues = allowedValues;
            return this;
        }

        /**
         * @param allowedValues The third-party client access values that can be set on organizations created for this client through the My Organization API. Required whenever this block is set — the API rejects the block without it. Possible values: `allow`, `block`. Unlike `auth0.ConnectionProfile`&#39;s `crossAppAccessResourceApp`, a single value is accepted here. (EA Only)
         * 
         * @return builder
         * 
         */
        public Builder allowedValues(List<String> allowedValues) {
            return allowedValues(Output.of(allowedValues));
        }

        /**
         * @param allowedValues The third-party client access values that can be set on organizations created for this client through the My Organization API. Required whenever this block is set — the API rejects the block without it. Possible values: `allow`, `block`. Unlike `auth0.ConnectionProfile`&#39;s `crossAppAccessResourceApp`, a single value is accepted here. (EA Only)
         * 
         * @return builder
         * 
         */
        public Builder allowedValues(String... allowedValues) {
            return allowedValues(List.of(allowedValues));
        }

        /**
         * @param defaultValue The default third-party client access value applied to organizations created for this client. The API currently only accepts &#34;block&#34;; &#34;allow&#34; is rejected with a 400 error, so this is exposed as computed-only rather than user-settable. (EA Only)
         * 
         * @return builder
         * 
         */
        public Builder defaultValue(@Nullable Output<String> defaultValue) {
            $.defaultValue = defaultValue;
            return this;
        }

        /**
         * @param defaultValue The default third-party client access value applied to organizations created for this client. The API currently only accepts &#34;block&#34;; &#34;allow&#34; is rejected with a 400 error, so this is exposed as computed-only rather than user-settable. (EA Only)
         * 
         * @return builder
         * 
         */
        public Builder defaultValue(String defaultValue) {
            return defaultValue(Output.of(defaultValue));
        }

        public ClientMyOrganizationConfigurationThirdPartyClientAccessArgs build() {
            if ($.allowedValues == null) {
                throw new MissingRequiredPropertyException("ClientMyOrganizationConfigurationThirdPartyClientAccessArgs", "allowedValues");
            }
            return $;
        }
    }

}
