// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.auth0.inputs;

import com.pulumi.auth0.inputs.ConnectionProfileStrategyOverridesAdArgs;
import com.pulumi.auth0.inputs.ConnectionProfileStrategyOverridesAdfsArgs;
import com.pulumi.auth0.inputs.ConnectionProfileStrategyOverridesGoogleAppsArgs;
import com.pulumi.auth0.inputs.ConnectionProfileStrategyOverridesOidcArgs;
import com.pulumi.auth0.inputs.ConnectionProfileStrategyOverridesOktaArgs;
import com.pulumi.auth0.inputs.ConnectionProfileStrategyOverridesPingfederateArgs;
import com.pulumi.auth0.inputs.ConnectionProfileStrategyOverridesSamlpArgs;
import com.pulumi.auth0.inputs.ConnectionProfileStrategyOverridesWaadArgs;
import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class ConnectionProfileStrategyOverridesArgs extends com.pulumi.resources.ResourceArgs {

    public static final ConnectionProfileStrategyOverridesArgs Empty = new ConnectionProfileStrategyOverridesArgs();

    /**
     * Strategy override configuration.
     * 
     */
    @Import(name="ad")
    private @Nullable Output<ConnectionProfileStrategyOverridesAdArgs> ad;

    /**
     * @return Strategy override configuration.
     * 
     */
    public Optional<Output<ConnectionProfileStrategyOverridesAdArgs>> ad() {
        return Optional.ofNullable(this.ad);
    }

    /**
     * Strategy override configuration.
     * 
     */
    @Import(name="adfs")
    private @Nullable Output<ConnectionProfileStrategyOverridesAdfsArgs> adfs;

    /**
     * @return Strategy override configuration.
     * 
     */
    public Optional<Output<ConnectionProfileStrategyOverridesAdfsArgs>> adfs() {
        return Optional.ofNullable(this.adfs);
    }

    /**
     * Strategy override configuration.
     * 
     */
    @Import(name="googleApps")
    private @Nullable Output<ConnectionProfileStrategyOverridesGoogleAppsArgs> googleApps;

    /**
     * @return Strategy override configuration.
     * 
     */
    public Optional<Output<ConnectionProfileStrategyOverridesGoogleAppsArgs>> googleApps() {
        return Optional.ofNullable(this.googleApps);
    }

    /**
     * Strategy override configuration.
     * 
     */
    @Import(name="oidc")
    private @Nullable Output<ConnectionProfileStrategyOverridesOidcArgs> oidc;

    /**
     * @return Strategy override configuration.
     * 
     */
    public Optional<Output<ConnectionProfileStrategyOverridesOidcArgs>> oidc() {
        return Optional.ofNullable(this.oidc);
    }

    /**
     * Strategy override configuration.
     * 
     */
    @Import(name="okta")
    private @Nullable Output<ConnectionProfileStrategyOverridesOktaArgs> okta;

    /**
     * @return Strategy override configuration.
     * 
     */
    public Optional<Output<ConnectionProfileStrategyOverridesOktaArgs>> okta() {
        return Optional.ofNullable(this.okta);
    }

    /**
     * Strategy override configuration.
     * 
     */
    @Import(name="pingfederate")
    private @Nullable Output<ConnectionProfileStrategyOverridesPingfederateArgs> pingfederate;

    /**
     * @return Strategy override configuration.
     * 
     */
    public Optional<Output<ConnectionProfileStrategyOverridesPingfederateArgs>> pingfederate() {
        return Optional.ofNullable(this.pingfederate);
    }

    /**
     * Strategy override configuration.
     * 
     */
    @Import(name="samlp")
    private @Nullable Output<ConnectionProfileStrategyOverridesSamlpArgs> samlp;

    /**
     * @return Strategy override configuration.
     * 
     */
    public Optional<Output<ConnectionProfileStrategyOverridesSamlpArgs>> samlp() {
        return Optional.ofNullable(this.samlp);
    }

    /**
     * Strategy override configuration.
     * 
     */
    @Import(name="waad")
    private @Nullable Output<ConnectionProfileStrategyOverridesWaadArgs> waad;

    /**
     * @return Strategy override configuration.
     * 
     */
    public Optional<Output<ConnectionProfileStrategyOverridesWaadArgs>> waad() {
        return Optional.ofNullable(this.waad);
    }

    private ConnectionProfileStrategyOverridesArgs() {}

    private ConnectionProfileStrategyOverridesArgs(ConnectionProfileStrategyOverridesArgs $) {
        this.ad = $.ad;
        this.adfs = $.adfs;
        this.googleApps = $.googleApps;
        this.oidc = $.oidc;
        this.okta = $.okta;
        this.pingfederate = $.pingfederate;
        this.samlp = $.samlp;
        this.waad = $.waad;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(ConnectionProfileStrategyOverridesArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private ConnectionProfileStrategyOverridesArgs $;

        public Builder() {
            $ = new ConnectionProfileStrategyOverridesArgs();
        }

        public Builder(ConnectionProfileStrategyOverridesArgs defaults) {
            $ = new ConnectionProfileStrategyOverridesArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param ad Strategy override configuration.
         * 
         * @return builder
         * 
         */
        public Builder ad(@Nullable Output<ConnectionProfileStrategyOverridesAdArgs> ad) {
            $.ad = ad;
            return this;
        }

        /**
         * @param ad Strategy override configuration.
         * 
         * @return builder
         * 
         */
        public Builder ad(ConnectionProfileStrategyOverridesAdArgs ad) {
            return ad(Output.of(ad));
        }

        /**
         * @param adfs Strategy override configuration.
         * 
         * @return builder
         * 
         */
        public Builder adfs(@Nullable Output<ConnectionProfileStrategyOverridesAdfsArgs> adfs) {
            $.adfs = adfs;
            return this;
        }

        /**
         * @param adfs Strategy override configuration.
         * 
         * @return builder
         * 
         */
        public Builder adfs(ConnectionProfileStrategyOverridesAdfsArgs adfs) {
            return adfs(Output.of(adfs));
        }

        /**
         * @param googleApps Strategy override configuration.
         * 
         * @return builder
         * 
         */
        public Builder googleApps(@Nullable Output<ConnectionProfileStrategyOverridesGoogleAppsArgs> googleApps) {
            $.googleApps = googleApps;
            return this;
        }

        /**
         * @param googleApps Strategy override configuration.
         * 
         * @return builder
         * 
         */
        public Builder googleApps(ConnectionProfileStrategyOverridesGoogleAppsArgs googleApps) {
            return googleApps(Output.of(googleApps));
        }

        /**
         * @param oidc Strategy override configuration.
         * 
         * @return builder
         * 
         */
        public Builder oidc(@Nullable Output<ConnectionProfileStrategyOverridesOidcArgs> oidc) {
            $.oidc = oidc;
            return this;
        }

        /**
         * @param oidc Strategy override configuration.
         * 
         * @return builder
         * 
         */
        public Builder oidc(ConnectionProfileStrategyOverridesOidcArgs oidc) {
            return oidc(Output.of(oidc));
        }

        /**
         * @param okta Strategy override configuration.
         * 
         * @return builder
         * 
         */
        public Builder okta(@Nullable Output<ConnectionProfileStrategyOverridesOktaArgs> okta) {
            $.okta = okta;
            return this;
        }

        /**
         * @param okta Strategy override configuration.
         * 
         * @return builder
         * 
         */
        public Builder okta(ConnectionProfileStrategyOverridesOktaArgs okta) {
            return okta(Output.of(okta));
        }

        /**
         * @param pingfederate Strategy override configuration.
         * 
         * @return builder
         * 
         */
        public Builder pingfederate(@Nullable Output<ConnectionProfileStrategyOverridesPingfederateArgs> pingfederate) {
            $.pingfederate = pingfederate;
            return this;
        }

        /**
         * @param pingfederate Strategy override configuration.
         * 
         * @return builder
         * 
         */
        public Builder pingfederate(ConnectionProfileStrategyOverridesPingfederateArgs pingfederate) {
            return pingfederate(Output.of(pingfederate));
        }

        /**
         * @param samlp Strategy override configuration.
         * 
         * @return builder
         * 
         */
        public Builder samlp(@Nullable Output<ConnectionProfileStrategyOverridesSamlpArgs> samlp) {
            $.samlp = samlp;
            return this;
        }

        /**
         * @param samlp Strategy override configuration.
         * 
         * @return builder
         * 
         */
        public Builder samlp(ConnectionProfileStrategyOverridesSamlpArgs samlp) {
            return samlp(Output.of(samlp));
        }

        /**
         * @param waad Strategy override configuration.
         * 
         * @return builder
         * 
         */
        public Builder waad(@Nullable Output<ConnectionProfileStrategyOverridesWaadArgs> waad) {
            $.waad = waad;
            return this;
        }

        /**
         * @param waad Strategy override configuration.
         * 
         * @return builder
         * 
         */
        public Builder waad(ConnectionProfileStrategyOverridesWaadArgs waad) {
            return waad(Output.of(waad));
        }

        public ConnectionProfileStrategyOverridesArgs build() {
            return $;
        }
    }

}
