// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.auth0.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;


public final class GetConnectionDirectoryArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetConnectionDirectoryArgs Empty = new GetConnectionDirectoryArgs();

    /**
     * ID of the connection for this directory provisioning configuration.
     * 
     */
    @Import(name="connectionId", required=true)
    private Output<String> connectionId;

    /**
     * @return ID of the connection for this directory provisioning configuration.
     * 
     */
    public Output<String> connectionId() {
        return this.connectionId;
    }

    private GetConnectionDirectoryArgs() {}

    private GetConnectionDirectoryArgs(GetConnectionDirectoryArgs $) {
        this.connectionId = $.connectionId;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetConnectionDirectoryArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetConnectionDirectoryArgs $;

        public Builder() {
            $ = new GetConnectionDirectoryArgs();
        }

        public Builder(GetConnectionDirectoryArgs defaults) {
            $ = new GetConnectionDirectoryArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param connectionId ID of the connection for this directory provisioning configuration.
         * 
         * @return builder
         * 
         */
        public Builder connectionId(Output<String> connectionId) {
            $.connectionId = connectionId;
            return this;
        }

        /**
         * @param connectionId ID of the connection for this directory provisioning configuration.
         * 
         * @return builder
         * 
         */
        public Builder connectionId(String connectionId) {
            return connectionId(Output.of(connectionId));
        }

        public GetConnectionDirectoryArgs build() {
            if ($.connectionId == null) {
                throw new MissingRequiredPropertyException("GetConnectionDirectoryArgs", "connectionId");
            }
            return $;
        }
    }

}
