// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.auth0.inputs;

import com.pulumi.auth0.inputs.GuardianPhoneOptionsArgs;
import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class GuardianPhoneArgs extends com.pulumi.resources.ResourceArgs {

    public static final GuardianPhoneArgs Empty = new GuardianPhoneArgs();

    /**
     * Message types to use, array of `sms` and/or `voice`. Adding both to the array should enable the user to choose.
     * 
     */
    @Import(name="messageTypes", required=true)
    private Output<List<String>> messageTypes;

    /**
     * @return Message types to use, array of `sms` and/or `voice`. Adding both to the array should enable the user to choose.
     * 
     */
    public Output<List<String>> messageTypes() {
        return this.messageTypes;
    }

    /**
     * Options for the various providers.
     * 
     */
    @Import(name="options")
    private @Nullable Output<GuardianPhoneOptionsArgs> options;

    /**
     * @return Options for the various providers.
     * 
     */
    public Optional<Output<GuardianPhoneOptionsArgs>> options() {
        return Optional.ofNullable(this.options);
    }

    /**
     * Provider to use, one of `auth0`, `twilio` or `phone-message-hook`.
     * 
     */
    @Import(name="provider", required=true)
    private Output<String> provider;

    /**
     * @return Provider to use, one of `auth0`, `twilio` or `phone-message-hook`.
     * 
     */
    public Output<String> provider() {
        return this.provider;
    }

    private GuardianPhoneArgs() {}

    private GuardianPhoneArgs(GuardianPhoneArgs $) {
        this.messageTypes = $.messageTypes;
        this.options = $.options;
        this.provider = $.provider;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GuardianPhoneArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GuardianPhoneArgs $;

        public Builder() {
            $ = new GuardianPhoneArgs();
        }

        public Builder(GuardianPhoneArgs defaults) {
            $ = new GuardianPhoneArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param messageTypes Message types to use, array of `sms` and/or `voice`. Adding both to the array should enable the user to choose.
         * 
         * @return builder
         * 
         */
        public Builder messageTypes(Output<List<String>> messageTypes) {
            $.messageTypes = messageTypes;
            return this;
        }

        /**
         * @param messageTypes Message types to use, array of `sms` and/or `voice`. Adding both to the array should enable the user to choose.
         * 
         * @return builder
         * 
         */
        public Builder messageTypes(List<String> messageTypes) {
            return messageTypes(Output.of(messageTypes));
        }

        /**
         * @param messageTypes Message types to use, array of `sms` and/or `voice`. Adding both to the array should enable the user to choose.
         * 
         * @return builder
         * 
         */
        public Builder messageTypes(String... messageTypes) {
            return messageTypes(List.of(messageTypes));
        }

        /**
         * @param options Options for the various providers.
         * 
         * @return builder
         * 
         */
        public Builder options(@Nullable Output<GuardianPhoneOptionsArgs> options) {
            $.options = options;
            return this;
        }

        /**
         * @param options Options for the various providers.
         * 
         * @return builder
         * 
         */
        public Builder options(GuardianPhoneOptionsArgs options) {
            return options(Output.of(options));
        }

        /**
         * @param provider Provider to use, one of `auth0`, `twilio` or `phone-message-hook`.
         * 
         * @return builder
         * 
         */
        public Builder provider(Output<String> provider) {
            $.provider = provider;
            return this;
        }

        /**
         * @param provider Provider to use, one of `auth0`, `twilio` or `phone-message-hook`.
         * 
         * @return builder
         * 
         */
        public Builder provider(String provider) {
            return provider(Output.of(provider));
        }

        public GuardianPhoneArgs build() {
            $.messageTypes = Objects.requireNonNull($.messageTypes, "expected parameter 'messageTypes' to be non-null");
            $.provider = Objects.requireNonNull($.provider, "expected parameter 'provider' to be non-null");
            return $;
        }
    }

}
