// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.auth0.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Integer;
import java.util.Objects;


public final class GuardianPhoneSettingsArgs extends com.pulumi.resources.ResourceArgs {

    public static final GuardianPhoneSettingsArgs Empty = new GuardianPhoneSettingsArgs();

    /**
     * The OTP expiration time in seconds. Defaults to `300` (5 minutes).
     * 
     */
    @Import(name="otpExpirationTime", required=true)
    private Output<Integer> otpExpirationTime;

    /**
     * @return The OTP expiration time in seconds. Defaults to `300` (5 minutes).
     * 
     */
    public Output<Integer> otpExpirationTime() {
        return this.otpExpirationTime;
    }

    /**
     * The length of the OTP code. Defaults to `6`.
     * 
     */
    @Import(name="otpLength", required=true)
    private Output<Integer> otpLength;

    /**
     * @return The length of the OTP code. Defaults to `6`.
     * 
     */
    public Output<Integer> otpLength() {
        return this.otpLength;
    }

    private GuardianPhoneSettingsArgs() {}

    private GuardianPhoneSettingsArgs(GuardianPhoneSettingsArgs $) {
        this.otpExpirationTime = $.otpExpirationTime;
        this.otpLength = $.otpLength;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GuardianPhoneSettingsArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GuardianPhoneSettingsArgs $;

        public Builder() {
            $ = new GuardianPhoneSettingsArgs();
        }

        public Builder(GuardianPhoneSettingsArgs defaults) {
            $ = new GuardianPhoneSettingsArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param otpExpirationTime The OTP expiration time in seconds. Defaults to `300` (5 minutes).
         * 
         * @return builder
         * 
         */
        public Builder otpExpirationTime(Output<Integer> otpExpirationTime) {
            $.otpExpirationTime = otpExpirationTime;
            return this;
        }

        /**
         * @param otpExpirationTime The OTP expiration time in seconds. Defaults to `300` (5 minutes).
         * 
         * @return builder
         * 
         */
        public Builder otpExpirationTime(Integer otpExpirationTime) {
            return otpExpirationTime(Output.of(otpExpirationTime));
        }

        /**
         * @param otpLength The length of the OTP code. Defaults to `6`.
         * 
         * @return builder
         * 
         */
        public Builder otpLength(Output<Integer> otpLength) {
            $.otpLength = otpLength;
            return this;
        }

        /**
         * @param otpLength The length of the OTP code. Defaults to `6`.
         * 
         * @return builder
         * 
         */
        public Builder otpLength(Integer otpLength) {
            return otpLength(Output.of(otpLength));
        }

        public GuardianPhoneSettingsArgs build() {
            if ($.otpExpirationTime == null) {
                throw new MissingRequiredPropertyException("GuardianPhoneSettingsArgs", "otpExpirationTime");
            }
            if ($.otpLength == null) {
                throw new MissingRequiredPropertyException("GuardianPhoneSettingsArgs", "otpLength");
            }
            return $;
        }
    }

}
