// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.auth0.inputs;

import com.pulumi.auth0.inputs.RateLimitPolicyConfigurationArgs;
import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class RateLimitPolicyState extends com.pulumi.resources.ResourceArgs {

    public static final RateLimitPolicyState Empty = new RateLimitPolicyState();

    /**
     * The throttling configuration applied when the rate limit is reached. (EA only)
     * 
     */
    @Import(name="configuration")
    private @Nullable Output<RateLimitPolicyConfigurationArgs> configuration;

    /**
     * @return The throttling configuration applied when the rate limit is reached. (EA only)
     * 
     */
    public Optional<Output<RateLimitPolicyConfigurationArgs>> configuration() {
        return Optional.ofNullable(this.configuration);
    }

    /**
     * The consumer category the policy applies to. Valid values are: client
     * 
     */
    @Import(name="consumer")
    private @Nullable Output<String> consumer;

    /**
     * @return The consumer category the policy applies to. Valid values are: client
     * 
     */
    public Optional<Output<String>> consumer() {
        return Optional.ofNullable(this.consumer);
    }

    /**
     * Identifier or category within the consumer to which the policy applies. Supported values: `client_id:&lt;client_id&gt;`, `client_id:&lt;cimd_uri&gt;`, `cimdClients`, `thirdPartyClients`, or `default`. (EA only)
     * 
     */
    @Import(name="consumerSelector")
    private @Nullable Output<String> consumerSelector;

    /**
     * @return Identifier or category within the consumer to which the policy applies. Supported values: `client_id:&lt;client_id&gt;`, `client_id:&lt;cimd_uri&gt;`, `cimdClients`, `thirdPartyClients`, or `default`. (EA only)
     * 
     */
    public Optional<Output<String>> consumerSelector() {
        return Optional.ofNullable(this.consumerSelector);
    }

    /**
     * The date and time when the rate limit policy was created.
     * 
     */
    @Import(name="createdAt")
    private @Nullable Output<String> createdAt;

    /**
     * @return The date and time when the rate limit policy was created.
     * 
     */
    public Optional<Output<String>> createdAt() {
        return Optional.ofNullable(this.createdAt);
    }

    /**
     * The resource the policy applies to. Valid values are: oauth*authentication*api
     * 
     */
    @Import(name="resource")
    private @Nullable Output<String> resource;

    /**
     * @return The resource the policy applies to. Valid values are: oauth*authentication*api
     * 
     */
    public Optional<Output<String>> resource() {
        return Optional.ofNullable(this.resource);
    }

    /**
     * The date and time when the rate limit policy was last updated.
     * 
     */
    @Import(name="updatedAt")
    private @Nullable Output<String> updatedAt;

    /**
     * @return The date and time when the rate limit policy was last updated.
     * 
     */
    public Optional<Output<String>> updatedAt() {
        return Optional.ofNullable(this.updatedAt);
    }

    private RateLimitPolicyState() {}

    private RateLimitPolicyState(RateLimitPolicyState $) {
        this.configuration = $.configuration;
        this.consumer = $.consumer;
        this.consumerSelector = $.consumerSelector;
        this.createdAt = $.createdAt;
        this.resource = $.resource;
        this.updatedAt = $.updatedAt;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(RateLimitPolicyState defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private RateLimitPolicyState $;

        public Builder() {
            $ = new RateLimitPolicyState();
        }

        public Builder(RateLimitPolicyState defaults) {
            $ = new RateLimitPolicyState(Objects.requireNonNull(defaults));
        }

        /**
         * @param configuration The throttling configuration applied when the rate limit is reached. (EA only)
         * 
         * @return builder
         * 
         */
        public Builder configuration(@Nullable Output<RateLimitPolicyConfigurationArgs> configuration) {
            $.configuration = configuration;
            return this;
        }

        /**
         * @param configuration The throttling configuration applied when the rate limit is reached. (EA only)
         * 
         * @return builder
         * 
         */
        public Builder configuration(RateLimitPolicyConfigurationArgs configuration) {
            return configuration(Output.of(configuration));
        }

        /**
         * @param consumer The consumer category the policy applies to. Valid values are: client
         * 
         * @return builder
         * 
         */
        public Builder consumer(@Nullable Output<String> consumer) {
            $.consumer = consumer;
            return this;
        }

        /**
         * @param consumer The consumer category the policy applies to. Valid values are: client
         * 
         * @return builder
         * 
         */
        public Builder consumer(String consumer) {
            return consumer(Output.of(consumer));
        }

        /**
         * @param consumerSelector Identifier or category within the consumer to which the policy applies. Supported values: `client_id:&lt;client_id&gt;`, `client_id:&lt;cimd_uri&gt;`, `cimdClients`, `thirdPartyClients`, or `default`. (EA only)
         * 
         * @return builder
         * 
         */
        public Builder consumerSelector(@Nullable Output<String> consumerSelector) {
            $.consumerSelector = consumerSelector;
            return this;
        }

        /**
         * @param consumerSelector Identifier or category within the consumer to which the policy applies. Supported values: `client_id:&lt;client_id&gt;`, `client_id:&lt;cimd_uri&gt;`, `cimdClients`, `thirdPartyClients`, or `default`. (EA only)
         * 
         * @return builder
         * 
         */
        public Builder consumerSelector(String consumerSelector) {
            return consumerSelector(Output.of(consumerSelector));
        }

        /**
         * @param createdAt The date and time when the rate limit policy was created.
         * 
         * @return builder
         * 
         */
        public Builder createdAt(@Nullable Output<String> createdAt) {
            $.createdAt = createdAt;
            return this;
        }

        /**
         * @param createdAt The date and time when the rate limit policy was created.
         * 
         * @return builder
         * 
         */
        public Builder createdAt(String createdAt) {
            return createdAt(Output.of(createdAt));
        }

        /**
         * @param resource The resource the policy applies to. Valid values are: oauth*authentication*api
         * 
         * @return builder
         * 
         */
        public Builder resource(@Nullable Output<String> resource) {
            $.resource = resource;
            return this;
        }

        /**
         * @param resource The resource the policy applies to. Valid values are: oauth*authentication*api
         * 
         * @return builder
         * 
         */
        public Builder resource(String resource) {
            return resource(Output.of(resource));
        }

        /**
         * @param updatedAt The date and time when the rate limit policy was last updated.
         * 
         * @return builder
         * 
         */
        public Builder updatedAt(@Nullable Output<String> updatedAt) {
            $.updatedAt = updatedAt;
            return this;
        }

        /**
         * @param updatedAt The date and time when the rate limit policy was last updated.
         * 
         * @return builder
         * 
         */
        public Builder updatedAt(String updatedAt) {
            return updatedAt(Output.of(updatedAt));
        }

        public RateLimitPolicyState build() {
            return $;
        }
    }

}
