// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.auth0.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.List;
import java.util.Objects;


public final class TenantCountryCodesArgs extends com.pulumi.resources.ResourceArgs {

    public static final TenantCountryCodesArgs Empty = new TenantCountryCodesArgs();

    /**
     * List of ISO 3166-1 alpha-2 country codes.
     * 
     */
    @Import(name="lists", required=true)
    private Output<List<String>> lists;

    /**
     * @return List of ISO 3166-1 alpha-2 country codes.
     * 
     */
    public Output<List<String>> lists() {
        return this.lists;
    }

    /**
     * Whether the list is an allow-list or deny-list. Available options: `allow`, `deny`.
     * 
     */
    @Import(name="mode", required=true)
    private Output<String> mode;

    /**
     * @return Whether the list is an allow-list or deny-list. Available options: `allow`, `deny`.
     * 
     */
    public Output<String> mode() {
        return this.mode;
    }

    private TenantCountryCodesArgs() {}

    private TenantCountryCodesArgs(TenantCountryCodesArgs $) {
        this.lists = $.lists;
        this.mode = $.mode;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(TenantCountryCodesArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private TenantCountryCodesArgs $;

        public Builder() {
            $ = new TenantCountryCodesArgs();
        }

        public Builder(TenantCountryCodesArgs defaults) {
            $ = new TenantCountryCodesArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param lists List of ISO 3166-1 alpha-2 country codes.
         * 
         * @return builder
         * 
         */
        public Builder lists(Output<List<String>> lists) {
            $.lists = lists;
            return this;
        }

        /**
         * @param lists List of ISO 3166-1 alpha-2 country codes.
         * 
         * @return builder
         * 
         */
        public Builder lists(List<String> lists) {
            return lists(Output.of(lists));
        }

        /**
         * @param lists List of ISO 3166-1 alpha-2 country codes.
         * 
         * @return builder
         * 
         */
        public Builder lists(String... lists) {
            return lists(List.of(lists));
        }

        /**
         * @param mode Whether the list is an allow-list or deny-list. Available options: `allow`, `deny`.
         * 
         * @return builder
         * 
         */
        public Builder mode(Output<String> mode) {
            $.mode = mode;
            return this;
        }

        /**
         * @param mode Whether the list is an allow-list or deny-list. Available options: `allow`, `deny`.
         * 
         * @return builder
         * 
         */
        public Builder mode(String mode) {
            return mode(Output.of(mode));
        }

        public TenantCountryCodesArgs build() {
            if ($.lists == null) {
                throw new MissingRequiredPropertyException("TenantCountryCodesArgs", "lists");
            }
            if ($.mode == null) {
                throw new MissingRequiredPropertyException("TenantCountryCodesArgs", "mode");
            }
            return $;
        }
    }

}
