// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.auth0.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.Integer;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class ConnectionOptionsTotp {
    /**
     * @return Integer. Length of the one-time password.
     * 
     */
    private final @Nullable Integer length;
    /**
     * @return Integer. Seconds between allowed generation of new passwords.
     * 
     */
    private final @Nullable Integer timeStep;

    @CustomType.Constructor
    private ConnectionOptionsTotp(
        @CustomType.Parameter("length") @Nullable Integer length,
        @CustomType.Parameter("timeStep") @Nullable Integer timeStep) {
        this.length = length;
        this.timeStep = timeStep;
    }

    /**
     * @return Integer. Length of the one-time password.
     * 
     */
    public Optional<Integer> length() {
        return Optional.ofNullable(this.length);
    }
    /**
     * @return Integer. Seconds between allowed generation of new passwords.
     * 
     */
    public Optional<Integer> timeStep() {
        return Optional.ofNullable(this.timeStep);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(ConnectionOptionsTotp defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private @Nullable Integer length;
        private @Nullable Integer timeStep;

        public Builder() {
    	      // Empty
        }

        public Builder(ConnectionOptionsTotp defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.length = defaults.length;
    	      this.timeStep = defaults.timeStep;
        }

        public Builder length(@Nullable Integer length) {
            this.length = length;
            return this;
        }
        public Builder timeStep(@Nullable Integer timeStep) {
            this.timeStep = timeStep;
            return this;
        }        public ConnectionOptionsTotp build() {
            return new ConnectionOptionsTotp(length, timeStep);
        }
    }
}
