// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.auth0.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.Object;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class CustomDomainVerification {
    /**
     * @return Contains error message, if any, from the last DNS verification check.
     * 
     */
    private @Nullable String errorMsg;
    /**
     * @return Indicates the last time the domain was successfully verified.
     * 
     */
    private @Nullable String lastVerifiedAt;
    /**
     * @return Defines the list of domain verification methods used.
     * 
     */
    private @Nullable List<Object> methods;
    /**
     * @return Represents the current status of the domain verification process.
     * 
     */
    private @Nullable String status;

    private CustomDomainVerification() {}
    /**
     * @return Contains error message, if any, from the last DNS verification check.
     * 
     */
    public Optional<String> errorMsg() {
        return Optional.ofNullable(this.errorMsg);
    }
    /**
     * @return Indicates the last time the domain was successfully verified.
     * 
     */
    public Optional<String> lastVerifiedAt() {
        return Optional.ofNullable(this.lastVerifiedAt);
    }
    /**
     * @return Defines the list of domain verification methods used.
     * 
     */
    public List<Object> methods() {
        return this.methods == null ? List.of() : this.methods;
    }
    /**
     * @return Represents the current status of the domain verification process.
     * 
     */
    public Optional<String> status() {
        return Optional.ofNullable(this.status);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(CustomDomainVerification defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable String errorMsg;
        private @Nullable String lastVerifiedAt;
        private @Nullable List<Object> methods;
        private @Nullable String status;
        public Builder() {}
        public Builder(CustomDomainVerification defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.errorMsg = defaults.errorMsg;
    	      this.lastVerifiedAt = defaults.lastVerifiedAt;
    	      this.methods = defaults.methods;
    	      this.status = defaults.status;
        }

        @CustomType.Setter
        public Builder errorMsg(@Nullable String errorMsg) {

            this.errorMsg = errorMsg;
            return this;
        }
        @CustomType.Setter
        public Builder lastVerifiedAt(@Nullable String lastVerifiedAt) {

            this.lastVerifiedAt = lastVerifiedAt;
            return this;
        }
        @CustomType.Setter
        public Builder methods(@Nullable List<Object> methods) {

            this.methods = methods;
            return this;
        }
        public Builder methods(Object... methods) {
            return methods(List.of(methods));
        }
        @CustomType.Setter
        public Builder status(@Nullable String status) {

            this.status = status;
            return this;
        }
        public CustomDomainVerification build() {
            final var _resultValue = new CustomDomainVerification();
            _resultValue.errorMsg = errorMsg;
            _resultValue.lastVerifiedAt = lastVerifiedAt;
            _resultValue.methods = methods;
            _resultValue.status = status;
            return _resultValue;
        }
    }
}
