// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.auth0.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Integer;
import java.lang.String;
import java.util.Objects;

@CustomType
public final class GetClientAddonAw {
    /**
     * @return AWS token lifetime in seconds.
     * 
     */
    private Integer lifetimeInSeconds;
    /**
     * @return AWS principal ARN, for example `arn:aws:iam::010616021751:saml-provider/idpname`.
     * 
     */
    private String principal;
    /**
     * @return AWS role ARN, for example `arn:aws:iam::010616021751:role/foo`.
     * 
     */
    private String role;

    private GetClientAddonAw() {}
    /**
     * @return AWS token lifetime in seconds.
     * 
     */
    public Integer lifetimeInSeconds() {
        return this.lifetimeInSeconds;
    }
    /**
     * @return AWS principal ARN, for example `arn:aws:iam::010616021751:saml-provider/idpname`.
     * 
     */
    public String principal() {
        return this.principal;
    }
    /**
     * @return AWS role ARN, for example `arn:aws:iam::010616021751:role/foo`.
     * 
     */
    public String role() {
        return this.role;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetClientAddonAw defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private Integer lifetimeInSeconds;
        private String principal;
        private String role;
        public Builder() {}
        public Builder(GetClientAddonAw defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.lifetimeInSeconds = defaults.lifetimeInSeconds;
    	      this.principal = defaults.principal;
    	      this.role = defaults.role;
        }

        @CustomType.Setter
        public Builder lifetimeInSeconds(Integer lifetimeInSeconds) {
            if (lifetimeInSeconds == null) {
              throw new MissingRequiredPropertyException("GetClientAddonAw", "lifetimeInSeconds");
            }
            this.lifetimeInSeconds = lifetimeInSeconds;
            return this;
        }
        @CustomType.Setter
        public Builder principal(String principal) {
            if (principal == null) {
              throw new MissingRequiredPropertyException("GetClientAddonAw", "principal");
            }
            this.principal = principal;
            return this;
        }
        @CustomType.Setter
        public Builder role(String role) {
            if (role == null) {
              throw new MissingRequiredPropertyException("GetClientAddonAw", "role");
            }
            this.role = role;
            return this;
        }
        public GetClientAddonAw build() {
            final var _resultValue = new GetClientAddonAw();
            _resultValue.lifetimeInSeconds = lifetimeInSeconds;
            _resultValue.principal = principal;
            _resultValue.role = role;
            return _resultValue;
        }
    }
}
