// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.auth0.outputs;

import com.pulumi.auth0.outputs.GetClientsClientFedcmLoginGoogle;
import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.util.List;
import java.util.Objects;

@CustomType
public final class GetClientsClientFedcmLogin {
    /**
     * @return Google FedCM configuration. (EA only)
     * 
     */
    private List<GetClientsClientFedcmLoginGoogle> googles;

    private GetClientsClientFedcmLogin() {}
    /**
     * @return Google FedCM configuration. (EA only)
     * 
     */
    public List<GetClientsClientFedcmLoginGoogle> googles() {
        return this.googles;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetClientsClientFedcmLogin defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private List<GetClientsClientFedcmLoginGoogle> googles;
        public Builder() {}
        public Builder(GetClientsClientFedcmLogin defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.googles = defaults.googles;
        }

        @CustomType.Setter
        public Builder googles(List<GetClientsClientFedcmLoginGoogle> googles) {
            if (googles == null) {
              throw new MissingRequiredPropertyException("GetClientsClientFedcmLogin", "googles");
            }
            this.googles = googles;
            return this;
        }
        public Builder googles(GetClientsClientFedcmLoginGoogle... googles) {
            return googles(List.of(googles));
        }
        public GetClientsClientFedcmLogin build() {
            final var _resultValue = new GetClientsClientFedcmLogin();
            _resultValue.googles = googles;
            return _resultValue;
        }
    }
}
