// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.auth0.outputs;

import com.pulumi.auth0.outputs.GetOutboundIpsChangelog;
import com.pulumi.auth0.outputs.GetOutboundIpsRegion;
import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.List;
import java.util.Objects;

@CustomType
public final class GetOutboundIpsResult {
    /**
     * @return List of recent changes to IP ranges.
     * 
     */
    private List<GetOutboundIpsChangelog> changelogs;
    /**
     * @return The ID of this resource.
     * 
     */
    private String id;
    /**
     * @return RFC3339 timestamp when the IP ranges were last updated.
     * 
     */
    private String lastUpdatedAt;
    /**
     * @return A list of regions and their corresponding IP CIDR blocks.
     * 
     */
    private List<GetOutboundIpsRegion> regions;

    private GetOutboundIpsResult() {}
    /**
     * @return List of recent changes to IP ranges.
     * 
     */
    public List<GetOutboundIpsChangelog> changelogs() {
        return this.changelogs;
    }
    /**
     * @return The ID of this resource.
     * 
     */
    public String id() {
        return this.id;
    }
    /**
     * @return RFC3339 timestamp when the IP ranges were last updated.
     * 
     */
    public String lastUpdatedAt() {
        return this.lastUpdatedAt;
    }
    /**
     * @return A list of regions and their corresponding IP CIDR blocks.
     * 
     */
    public List<GetOutboundIpsRegion> regions() {
        return this.regions;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetOutboundIpsResult defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private List<GetOutboundIpsChangelog> changelogs;
        private String id;
        private String lastUpdatedAt;
        private List<GetOutboundIpsRegion> regions;
        public Builder() {}
        public Builder(GetOutboundIpsResult defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.changelogs = defaults.changelogs;
    	      this.id = defaults.id;
    	      this.lastUpdatedAt = defaults.lastUpdatedAt;
    	      this.regions = defaults.regions;
        }

        @CustomType.Setter
        public Builder changelogs(List<GetOutboundIpsChangelog> changelogs) {
            if (changelogs == null) {
              throw new MissingRequiredPropertyException("GetOutboundIpsResult", "changelogs");
            }
            this.changelogs = changelogs;
            return this;
        }
        public Builder changelogs(GetOutboundIpsChangelog... changelogs) {
            return changelogs(List.of(changelogs));
        }
        @CustomType.Setter
        public Builder id(String id) {
            if (id == null) {
              throw new MissingRequiredPropertyException("GetOutboundIpsResult", "id");
            }
            this.id = id;
            return this;
        }
        @CustomType.Setter
        public Builder lastUpdatedAt(String lastUpdatedAt) {
            if (lastUpdatedAt == null) {
              throw new MissingRequiredPropertyException("GetOutboundIpsResult", "lastUpdatedAt");
            }
            this.lastUpdatedAt = lastUpdatedAt;
            return this;
        }
        @CustomType.Setter
        public Builder regions(List<GetOutboundIpsRegion> regions) {
            if (regions == null) {
              throw new MissingRequiredPropertyException("GetOutboundIpsResult", "regions");
            }
            this.regions = regions;
            return this;
        }
        public Builder regions(GetOutboundIpsRegion... regions) {
            return regions(List.of(regions));
        }
        public GetOutboundIpsResult build() {
            final var _resultValue = new GetOutboundIpsResult();
            _resultValue.changelogs = changelogs;
            _resultValue.id = id;
            _resultValue.lastUpdatedAt = lastUpdatedAt;
            _resultValue.regions = regions;
            return _resultValue;
        }
    }
}
