// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.auth0.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.Boolean;
import java.lang.String;
import java.util.Objects;

@CustomType
public final class TenantGuardianMfaPage {
    /**
     * @return Boolean. Indicates whether to use the custom Guardian page.
     * 
     */
    private final Boolean enabled;
    /**
     * @return String, HTML format with supported Liquid syntax. Customized content of the Guardian page.
     * 
     */
    private final String html;

    @CustomType.Constructor
    private TenantGuardianMfaPage(
        @CustomType.Parameter("enabled") Boolean enabled,
        @CustomType.Parameter("html") String html) {
        this.enabled = enabled;
        this.html = html;
    }

    /**
     * @return Boolean. Indicates whether to use the custom Guardian page.
     * 
     */
    public Boolean enabled() {
        return this.enabled;
    }
    /**
     * @return String, HTML format with supported Liquid syntax. Customized content of the Guardian page.
     * 
     */
    public String html() {
        return this.html;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(TenantGuardianMfaPage defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private Boolean enabled;
        private String html;

        public Builder() {
    	      // Empty
        }

        public Builder(TenantGuardianMfaPage defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.enabled = defaults.enabled;
    	      this.html = defaults.html;
        }

        public Builder enabled(Boolean enabled) {
            this.enabled = Objects.requireNonNull(enabled);
            return this;
        }
        public Builder html(String html) {
            this.html = Objects.requireNonNull(html);
            return this;
        }        public TenantGuardianMfaPage build() {
            return new TenantGuardianMfaPage(enabled, html);
        }
    }
}
