// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Auth0.Inputs
{

    public sealed class ClientCredentialsTokenVaultPrivilegedAccessGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("credentials", required: true)]
        private InputList<Inputs.ClientCredentialsTokenVaultPrivilegedAccessCredentialGetArgs>? _credentials;

        /// <summary>
        /// Credentials the privileged worker may authenticate with. A maximum of 2 client credentials can be set.
        /// </summary>
        public InputList<Inputs.ClientCredentialsTokenVaultPrivilegedAccessCredentialGetArgs> Credentials
        {
            get => _credentials ?? (_credentials = new InputList<Inputs.ClientCredentialsTokenVaultPrivilegedAccessCredentialGetArgs>());
            set => _credentials = value;
        }

        [Input("grants")]
        private InputList<Inputs.ClientCredentialsTokenVaultPrivilegedAccessGrantGetArgs>? _grants;

        /// <summary>
        /// Pins the connections, and the scopes within them, that the privileged worker may request tokens for. A maximum of 5 grants can be set, with a maximum of 20 scopes in total across all of them. Omit every `Grants` block to clear the grants already configured.
        /// </summary>
        public InputList<Inputs.ClientCredentialsTokenVaultPrivilegedAccessGrantGetArgs> Grants
        {
            get => _grants ?? (_grants = new InputList<Inputs.ClientCredentialsTokenVaultPrivilegedAccessGrantGetArgs>());
            set => _grants = value;
        }

        [Input("ipAllowlists", required: true)]
        private InputList<string>? _ipAllowlists;

        /// <summary>
        /// Permitted IPv4 or IPv6 addresses, or CIDR ranges, from which the privileged worker may request tokens. A maximum of 10 entries can be set. Set to `[]` to clear the entries already configured.
        /// </summary>
        public InputList<string> IpAllowlists
        {
            get => _ipAllowlists ?? (_ipAllowlists = new InputList<string>());
            set => _ipAllowlists = value;
        }

        public ClientCredentialsTokenVaultPrivilegedAccessGetArgs()
        {
        }
        public static new ClientCredentialsTokenVaultPrivilegedAccessGetArgs Empty => new ClientCredentialsTokenVaultPrivilegedAccessGetArgs();
    }
}
