// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Auth0.Inputs
{

    public sealed class ConnectionOptionsAttributeEmailGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("identifiers")]
        private InputList<Inputs.ConnectionOptionsAttributeEmailIdentifierGetArgs>? _identifiers;

        /// <summary>
        /// Connection Options Email Attribute Identifier
        /// </summary>
        public InputList<Inputs.ConnectionOptionsAttributeEmailIdentifierGetArgs> Identifiers
        {
            get => _identifiers ?? (_identifiers = new InputList<Inputs.ConnectionOptionsAttributeEmailIdentifierGetArgs>());
            set => _identifiers = value;
        }

        /// <summary>
        /// Defines whether Profile is required
        /// </summary>
        [Input("profileRequired")]
        public Input<bool>? ProfileRequired { get; set; }

        [Input("signups")]
        private InputList<Inputs.ConnectionOptionsAttributeEmailSignupGetArgs>? _signups;

        /// <summary>
        /// Defines signup settings for Email attribute
        /// </summary>
        public InputList<Inputs.ConnectionOptionsAttributeEmailSignupGetArgs> Signups
        {
            get => _signups ?? (_signups = new InputList<Inputs.ConnectionOptionsAttributeEmailSignupGetArgs>());
            set => _signups = value;
        }

        /// <summary>
        /// If set to false, it allow multiple accounts with the same email address. Defaults to `True`. This can only be set when the connection is created: the Auth0 Management API does not allow updating it, so changing it on an existing connection fails at plan time and requires recreating the connection. The API also refuses to add a non-unique email attribute to a connection that does not already have one.
        /// </summary>
        [Input("unique")]
        public Input<bool>? Unique { get; set; }

        /// <summary>
        /// Defines whether whether user will receive a link or an OTP during user signup for email verification and password reset for email verification
        /// </summary>
        [Input("verificationMethod")]
        public Input<string>? VerificationMethod { get; set; }

        public ConnectionOptionsAttributeEmailGetArgs()
        {
        }
        public static new ConnectionOptionsAttributeEmailGetArgs Empty => new ConnectionOptionsAttributeEmailGetArgs();
    }
}
