// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Auth0.Inputs
{

    public sealed class ConnectionProfileStrategyOverridesArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Strategy override configuration.
        /// </summary>
        [Input("ad")]
        public Input<Inputs.ConnectionProfileStrategyOverridesAdArgs>? Ad { get; set; }

        /// <summary>
        /// Strategy override configuration.
        /// </summary>
        [Input("adfs")]
        public Input<Inputs.ConnectionProfileStrategyOverridesAdfsArgs>? Adfs { get; set; }

        /// <summary>
        /// Strategy override configuration.
        /// </summary>
        [Input("googleApps")]
        public Input<Inputs.ConnectionProfileStrategyOverridesGoogleAppsArgs>? GoogleApps { get; set; }

        /// <summary>
        /// Strategy override configuration.
        /// </summary>
        [Input("oidc")]
        public Input<Inputs.ConnectionProfileStrategyOverridesOidcArgs>? Oidc { get; set; }

        /// <summary>
        /// Strategy override configuration.
        /// </summary>
        [Input("okta")]
        public Input<Inputs.ConnectionProfileStrategyOverridesOktaArgs>? Okta { get; set; }

        /// <summary>
        /// Strategy override configuration.
        /// </summary>
        [Input("pingfederate")]
        public Input<Inputs.ConnectionProfileStrategyOverridesPingfederateArgs>? Pingfederate { get; set; }

        /// <summary>
        /// Strategy override configuration.
        /// </summary>
        [Input("samlp")]
        public Input<Inputs.ConnectionProfileStrategyOverridesSamlpArgs>? Samlp { get; set; }

        /// <summary>
        /// Strategy override configuration.
        /// </summary>
        [Input("waad")]
        public Input<Inputs.ConnectionProfileStrategyOverridesWaadArgs>? Waad { get; set; }

        public ConnectionProfileStrategyOverridesArgs()
        {
        }
        public static new ConnectionProfileStrategyOverridesArgs Empty => new ConnectionProfileStrategyOverridesArgs();
    }
}
