// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * Data source to retrieve a specific Auth0 role by `roleId` or `name`.
 *
 * ## Example Usage
 *
 * <!--Start PulumiCodeChooser -->
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as auth0 from "@pulumi/auth0";
 *
 * const some-role-by-name = auth0.getRole({
 *     name: "my-role",
 * });
 * const some-role-by-id = auth0.getRole({
 *     roleId: "abcdefghkijklmnopqrstuvwxyz0123456789",
 * });
 * ```
 * <!--End PulumiCodeChooser -->
 */
export function getRole(args?: GetRoleArgs, opts?: pulumi.InvokeOptions): Promise<GetRoleResult> {
    args = args || {};

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("auth0:index/getRole:getRole", {
        "name": args.name,
        "roleId": args.roleId,
    }, opts);
}

/**
 * A collection of arguments for invoking getRole.
 */
export interface GetRoleArgs {
    name?: string;
    /**
     * The ID of the role. If not provided, `name` must be set.
     */
    roleId?: string;
}

/**
 * A collection of values returned by getRole.
 */
export interface GetRoleResult {
    /**
     * The description of the role.
     */
    readonly description: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    /**
     * The name of the role. If not provided, `roleId` must be set.
     */
    readonly name?: string;
    /**
     * Configuration settings for permissions (scopes) attached to the role.
     */
    readonly permissions: outputs.GetRolePermission[];
    /**
     * The ID of the role. If not provided, `name` must be set.
     */
    readonly roleId?: string;
    /**
     * List of user IDs assigned to this role. Retrieves a maximum of 1000 user IDs.
     */
    readonly users: string[];
}
/**
 * Data source to retrieve a specific Auth0 role by `roleId` or `name`.
 *
 * ## Example Usage
 *
 * <!--Start PulumiCodeChooser -->
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as auth0 from "@pulumi/auth0";
 *
 * const some-role-by-name = auth0.getRole({
 *     name: "my-role",
 * });
 * const some-role-by-id = auth0.getRole({
 *     roleId: "abcdefghkijklmnopqrstuvwxyz0123456789",
 * });
 * ```
 * <!--End PulumiCodeChooser -->
 */
export function getRoleOutput(args?: GetRoleOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetRoleResult> {
    return pulumi.output(args).apply((a: any) => getRole(a, opts))
}

/**
 * A collection of arguments for invoking getRole.
 */
export interface GetRoleOutputArgs {
    name?: pulumi.Input<string>;
    /**
     * The ID of the role. If not provided, `name` must be set.
     */
    roleId?: pulumi.Input<string>;
}
