// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs } from "./types";
import * as utilities from "./utilities";

export class GlobalClient extends pulumi.CustomResource {
    /**
     * Get an existing GlobalClient resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: GlobalClientState, opts?: pulumi.CustomResourceOptions): GlobalClient {
        return new GlobalClient(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'auth0:index/globalClient:GlobalClient';

    /**
     * Returns true if the given object is an instance of GlobalClient.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is GlobalClient {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === GlobalClient.__pulumiType;
    }

    public readonly addons!: pulumi.Output<outputs.GlobalClientAddons>;
    public readonly allowedClients!: pulumi.Output<string[]>;
    public readonly allowedLogoutUrls!: pulumi.Output<string[]>;
    public readonly allowedOrigins!: pulumi.Output<string[]>;
    public readonly appType!: pulumi.Output<string>;
    public readonly callbacks!: pulumi.Output<string[]>;
    public readonly clientId!: pulumi.Output<string>;
    public readonly clientMetadata!: pulumi.Output<{[key: string]: any}>;
    public readonly clientSecret!: pulumi.Output<string>;
    public readonly clientSecretRotationTrigger!: pulumi.Output<{[key: string]: any} | undefined>;
    public readonly crossOriginAuth!: pulumi.Output<boolean>;
    public readonly crossOriginLoc!: pulumi.Output<string>;
    public readonly customLoginPage!: pulumi.Output<string>;
    public readonly customLoginPageOn!: pulumi.Output<boolean>;
    public readonly description!: pulumi.Output<string>;
    public readonly encryptionKey!: pulumi.Output<{[key: string]: string}>;
    public readonly formTemplate!: pulumi.Output<string>;
    public readonly grantTypes!: pulumi.Output<string[]>;
    public readonly initiateLoginUri!: pulumi.Output<string>;
    public readonly isFirstParty!: pulumi.Output<boolean>;
    public readonly isTokenEndpointIpHeaderTrusted!: pulumi.Output<boolean>;
    public readonly jwtConfiguration!: pulumi.Output<outputs.GlobalClientJwtConfiguration>;
    public readonly logoUri!: pulumi.Output<string>;
    public readonly mobile!: pulumi.Output<outputs.GlobalClientMobile>;
    public readonly name!: pulumi.Output<string>;
    public readonly oidcConformant!: pulumi.Output<boolean>;
    public readonly organizationRequireBehavior!: pulumi.Output<string>;
    public readonly organizationUsage!: pulumi.Output<string>;
    public readonly refreshToken!: pulumi.Output<outputs.GlobalClientRefreshToken>;
    public readonly sso!: pulumi.Output<boolean>;
    public readonly ssoDisabled!: pulumi.Output<boolean>;
    public readonly tokenEndpointAuthMethod!: pulumi.Output<string>;
    public readonly webOrigins!: pulumi.Output<string[]>;

    /**
     * Create a GlobalClient resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: GlobalClientArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: GlobalClientArgs | GlobalClientState, opts?: pulumi.CustomResourceOptions) {
        let inputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as GlobalClientState | undefined;
            inputs["addons"] = state ? state.addons : undefined;
            inputs["allowedClients"] = state ? state.allowedClients : undefined;
            inputs["allowedLogoutUrls"] = state ? state.allowedLogoutUrls : undefined;
            inputs["allowedOrigins"] = state ? state.allowedOrigins : undefined;
            inputs["appType"] = state ? state.appType : undefined;
            inputs["callbacks"] = state ? state.callbacks : undefined;
            inputs["clientId"] = state ? state.clientId : undefined;
            inputs["clientMetadata"] = state ? state.clientMetadata : undefined;
            inputs["clientSecret"] = state ? state.clientSecret : undefined;
            inputs["clientSecretRotationTrigger"] = state ? state.clientSecretRotationTrigger : undefined;
            inputs["crossOriginAuth"] = state ? state.crossOriginAuth : undefined;
            inputs["crossOriginLoc"] = state ? state.crossOriginLoc : undefined;
            inputs["customLoginPage"] = state ? state.customLoginPage : undefined;
            inputs["customLoginPageOn"] = state ? state.customLoginPageOn : undefined;
            inputs["description"] = state ? state.description : undefined;
            inputs["encryptionKey"] = state ? state.encryptionKey : undefined;
            inputs["formTemplate"] = state ? state.formTemplate : undefined;
            inputs["grantTypes"] = state ? state.grantTypes : undefined;
            inputs["initiateLoginUri"] = state ? state.initiateLoginUri : undefined;
            inputs["isFirstParty"] = state ? state.isFirstParty : undefined;
            inputs["isTokenEndpointIpHeaderTrusted"] = state ? state.isTokenEndpointIpHeaderTrusted : undefined;
            inputs["jwtConfiguration"] = state ? state.jwtConfiguration : undefined;
            inputs["logoUri"] = state ? state.logoUri : undefined;
            inputs["mobile"] = state ? state.mobile : undefined;
            inputs["name"] = state ? state.name : undefined;
            inputs["oidcConformant"] = state ? state.oidcConformant : undefined;
            inputs["organizationRequireBehavior"] = state ? state.organizationRequireBehavior : undefined;
            inputs["organizationUsage"] = state ? state.organizationUsage : undefined;
            inputs["refreshToken"] = state ? state.refreshToken : undefined;
            inputs["sso"] = state ? state.sso : undefined;
            inputs["ssoDisabled"] = state ? state.ssoDisabled : undefined;
            inputs["tokenEndpointAuthMethod"] = state ? state.tokenEndpointAuthMethod : undefined;
            inputs["webOrigins"] = state ? state.webOrigins : undefined;
        } else {
            const args = argsOrState as GlobalClientArgs | undefined;
            inputs["addons"] = args ? args.addons : undefined;
            inputs["allowedClients"] = args ? args.allowedClients : undefined;
            inputs["allowedLogoutUrls"] = args ? args.allowedLogoutUrls : undefined;
            inputs["allowedOrigins"] = args ? args.allowedOrigins : undefined;
            inputs["appType"] = args ? args.appType : undefined;
            inputs["callbacks"] = args ? args.callbacks : undefined;
            inputs["clientId"] = args ? args.clientId : undefined;
            inputs["clientMetadata"] = args ? args.clientMetadata : undefined;
            inputs["clientSecret"] = args ? args.clientSecret : undefined;
            inputs["clientSecretRotationTrigger"] = args ? args.clientSecretRotationTrigger : undefined;
            inputs["crossOriginAuth"] = args ? args.crossOriginAuth : undefined;
            inputs["crossOriginLoc"] = args ? args.crossOriginLoc : undefined;
            inputs["customLoginPage"] = args ? args.customLoginPage : undefined;
            inputs["customLoginPageOn"] = args ? args.customLoginPageOn : undefined;
            inputs["description"] = args ? args.description : undefined;
            inputs["encryptionKey"] = args ? args.encryptionKey : undefined;
            inputs["formTemplate"] = args ? args.formTemplate : undefined;
            inputs["grantTypes"] = args ? args.grantTypes : undefined;
            inputs["initiateLoginUri"] = args ? args.initiateLoginUri : undefined;
            inputs["isFirstParty"] = args ? args.isFirstParty : undefined;
            inputs["isTokenEndpointIpHeaderTrusted"] = args ? args.isTokenEndpointIpHeaderTrusted : undefined;
            inputs["jwtConfiguration"] = args ? args.jwtConfiguration : undefined;
            inputs["logoUri"] = args ? args.logoUri : undefined;
            inputs["mobile"] = args ? args.mobile : undefined;
            inputs["name"] = args ? args.name : undefined;
            inputs["oidcConformant"] = args ? args.oidcConformant : undefined;
            inputs["organizationRequireBehavior"] = args ? args.organizationRequireBehavior : undefined;
            inputs["organizationUsage"] = args ? args.organizationUsage : undefined;
            inputs["refreshToken"] = args ? args.refreshToken : undefined;
            inputs["sso"] = args ? args.sso : undefined;
            inputs["ssoDisabled"] = args ? args.ssoDisabled : undefined;
            inputs["tokenEndpointAuthMethod"] = args ? args.tokenEndpointAuthMethod : undefined;
            inputs["webOrigins"] = args ? args.webOrigins : undefined;
        }
        if (!opts.version) {
            opts = pulumi.mergeOptions(opts, { version: utilities.getVersion()});
        }
        super(GlobalClient.__pulumiType, name, inputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering GlobalClient resources.
 */
export interface GlobalClientState {
    addons?: pulumi.Input<inputs.GlobalClientAddons>;
    allowedClients?: pulumi.Input<pulumi.Input<string>[]>;
    allowedLogoutUrls?: pulumi.Input<pulumi.Input<string>[]>;
    allowedOrigins?: pulumi.Input<pulumi.Input<string>[]>;
    appType?: pulumi.Input<string>;
    callbacks?: pulumi.Input<pulumi.Input<string>[]>;
    clientId?: pulumi.Input<string>;
    clientMetadata?: pulumi.Input<{[key: string]: any}>;
    clientSecret?: pulumi.Input<string>;
    clientSecretRotationTrigger?: pulumi.Input<{[key: string]: any}>;
    crossOriginAuth?: pulumi.Input<boolean>;
    crossOriginLoc?: pulumi.Input<string>;
    customLoginPage?: pulumi.Input<string>;
    customLoginPageOn?: pulumi.Input<boolean>;
    description?: pulumi.Input<string>;
    encryptionKey?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    formTemplate?: pulumi.Input<string>;
    grantTypes?: pulumi.Input<pulumi.Input<string>[]>;
    initiateLoginUri?: pulumi.Input<string>;
    isFirstParty?: pulumi.Input<boolean>;
    isTokenEndpointIpHeaderTrusted?: pulumi.Input<boolean>;
    jwtConfiguration?: pulumi.Input<inputs.GlobalClientJwtConfiguration>;
    logoUri?: pulumi.Input<string>;
    mobile?: pulumi.Input<inputs.GlobalClientMobile>;
    name?: pulumi.Input<string>;
    oidcConformant?: pulumi.Input<boolean>;
    organizationRequireBehavior?: pulumi.Input<string>;
    organizationUsage?: pulumi.Input<string>;
    refreshToken?: pulumi.Input<inputs.GlobalClientRefreshToken>;
    sso?: pulumi.Input<boolean>;
    ssoDisabled?: pulumi.Input<boolean>;
    tokenEndpointAuthMethod?: pulumi.Input<string>;
    webOrigins?: pulumi.Input<pulumi.Input<string>[]>;
}

/**
 * The set of arguments for constructing a GlobalClient resource.
 */
export interface GlobalClientArgs {
    addons?: pulumi.Input<inputs.GlobalClientAddons>;
    allowedClients?: pulumi.Input<pulumi.Input<string>[]>;
    allowedLogoutUrls?: pulumi.Input<pulumi.Input<string>[]>;
    allowedOrigins?: pulumi.Input<pulumi.Input<string>[]>;
    appType?: pulumi.Input<string>;
    callbacks?: pulumi.Input<pulumi.Input<string>[]>;
    clientId?: pulumi.Input<string>;
    clientMetadata?: pulumi.Input<{[key: string]: any}>;
    clientSecret?: pulumi.Input<string>;
    clientSecretRotationTrigger?: pulumi.Input<{[key: string]: any}>;
    crossOriginAuth?: pulumi.Input<boolean>;
    crossOriginLoc?: pulumi.Input<string>;
    customLoginPage?: pulumi.Input<string>;
    customLoginPageOn?: pulumi.Input<boolean>;
    description?: pulumi.Input<string>;
    encryptionKey?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    formTemplate?: pulumi.Input<string>;
    grantTypes?: pulumi.Input<pulumi.Input<string>[]>;
    initiateLoginUri?: pulumi.Input<string>;
    isFirstParty?: pulumi.Input<boolean>;
    isTokenEndpointIpHeaderTrusted?: pulumi.Input<boolean>;
    jwtConfiguration?: pulumi.Input<inputs.GlobalClientJwtConfiguration>;
    logoUri?: pulumi.Input<string>;
    mobile?: pulumi.Input<inputs.GlobalClientMobile>;
    name?: pulumi.Input<string>;
    oidcConformant?: pulumi.Input<boolean>;
    organizationRequireBehavior?: pulumi.Input<string>;
    organizationUsage?: pulumi.Input<string>;
    refreshToken?: pulumi.Input<inputs.GlobalClientRefreshToken>;
    sso?: pulumi.Input<boolean>;
    ssoDisabled?: pulumi.Input<boolean>;
    tokenEndpointAuthMethod?: pulumi.Input<string>;
    webOrigins?: pulumi.Input<pulumi.Input<string>[]>;
}
