// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * With this resource, you can set up APIs that can be consumed from your authorized applications.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as auth0 from "@pulumi/auth0";
 *
 * const myResourceServer = new auth0.ResourceServer("my_resource_server", {
 *     name: "Example Resource Server (Managed by Terraform)",
 *     identifier: "https://api.example.com",
 *     signingAlg: "RS256",
 *     allowOfflineAccess: true,
 *     tokenLifetime: 8600,
 *     skipConsentForVerifiableFirstPartyClients: true,
 *     consentPolicy: "transactional-authorization-with-mfa",
 *     tokenEncryption: {
 *         format: "compact-nested-jwe",
 *         encryptionKey: {
 *             name: "keyname",
 *             algorithm: "RSA-OAEP-256",
 *             pem: `-----BEGIN CERTIFICATE-----
 * MIIFWDCCA0ACCQDXqpBo3R...G9w0BAQsFADBuMQswCQYDVQQGEwJl
 * -----END CERTIFICATE-----
 * `,
 *         },
 *     },
 *     authorizationDetails: [
 *         {
 *             type: "payment",
 *         },
 *         {
 *             type: "non-payment",
 *         },
 *     ],
 *     proofOfPossession: {
 *         mechanism: "mtls",
 *         required: true,
 *     },
 *     subjectTypeAuthorization: {
 *         user: {
 *             policy: "allow_all",
 *         },
 *         client: {
 *             policy: "require_client_grant",
 *         },
 *     },
 * });
 * ```
 *
 * ## Import
 *
 * Existing resource servers can be imported using their ID.
 *
 * Example:
 *
 * ```sh
 * $ pulumi import auth0:index/resourceServer:ResourceServer my_resource_server "XXXXXXXXXXXXXXXXXXXXXXX"
 * ```
 */
export class ResourceServer extends pulumi.CustomResource {
    /**
     * Get an existing ResourceServer resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: ResourceServerState, opts?: pulumi.CustomResourceOptions): ResourceServer {
        return new ResourceServer(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'auth0:index/resourceServer:ResourceServer';

    /**
     * Returns true if the given object is an instance of ResourceServer.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is ResourceServer {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === ResourceServer.__pulumiType;
    }

    /**
     * Indicates whether refresh tokens can be issued for this resource server.
     */
    declare public readonly allowOfflineAccess: pulumi.Output<boolean | undefined>;
    /**
     * Authorization details for this resource server.
     */
    declare public readonly authorizationDetails: pulumi.Output<outputs.ResourceServerAuthorizationDetail[]>;
    /**
     * The ID of the client associated with this resource server. If a client has been created and linked to this resource server, this field will be populated with that client's ID.
     */
    declare public /*out*/ readonly clientId: pulumi.Output<string>;
    /**
     * Consent policy for this resource server. Options include `transactional-authorization-with-mfa`, or `null` to disable.
     */
    declare public readonly consentPolicy: pulumi.Output<string>;
    /**
     * If this setting is enabled, RBAC authorization policies will be enforced for this API. Role and permission assignments will be evaluated during the login transaction.
     */
    declare public readonly enforcePolicies: pulumi.Output<boolean>;
    /**
     * Unique identifier for the resource server. Used as the audience parameter for authorization calls. Cannot be changed once set.
     */
    declare public readonly identifier: pulumi.Output<string>;
    /**
     * Indicates whether this resource server is a special resource server created by Auth0. It cannot be modified or deleted directly.
     */
    declare public /*out*/ readonly isSystem: pulumi.Output<boolean>;
    /**
     * Friendly name for the resource server. Cannot include `<` or `>` characters.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * Configuration settings for proof-of-possession for this resource server.
     */
    declare public readonly proofOfPossession: pulumi.Output<outputs.ResourceServerProofOfPossession>;
    /**
     * Algorithm used to sign JWTs. Options include `HS256`, `RS256`, and `PS256`.
     */
    declare public readonly signingAlg: pulumi.Output<string>;
    /**
     * Secret used to sign tokens when using symmetric algorithms (HS256).
     */
    declare public readonly signingSecret: pulumi.Output<string>;
    /**
     * Indicates whether to skip user consent for applications flagged as first party.
     */
    declare public readonly skipConsentForVerifiableFirstPartyClients: pulumi.Output<boolean>;
    /**
     * Authorization policies for user and client flows.
     */
    declare public readonly subjectTypeAuthorization: pulumi.Output<outputs.ResourceServerSubjectTypeAuthorization>;
    /**
     * Dialect of access tokens that should be issued for this resource server. Options include `accessToken`, `rfc9068Profile`, `accessTokenAuthz`, and `rfc9068ProfileAuthz`. `accessToken` is a JWT containing standard Auth0 claims. `rfc9068Profile` is a JWT conforming to the IETF JWT Access Token Profile. `accessTokenAuthz` is a JWT containing standard Auth0 claims, including RBAC permissions claims. `rfc9068ProfileAuthz` is a JWT conforming to the IETF JWT Access Token Profile, including RBAC permissions claims. RBAC permissions claims are available if RBAC (`enforcePolicies`) is enabled for this API. For more details, refer to [Access Token Profiles](https://auth0.com/docs/secure/tokens/access-tokens/access-token-profiles).
     */
    declare public readonly tokenDialect: pulumi.Output<string>;
    /**
     * Configuration for JSON Web Encryption(JWE) of tokens for this resource server.
     */
    declare public readonly tokenEncryption: pulumi.Output<outputs.ResourceServerTokenEncryption>;
    /**
     * Number of seconds during which access tokens issued for this resource server from the token endpoint remain valid.
     */
    declare public readonly tokenLifetime: pulumi.Output<number>;
    /**
     * Number of seconds during which access tokens issued for this resource server via implicit or hybrid flows remain valid. Cannot be greater than the `tokenLifetime` value.
     */
    declare public readonly tokenLifetimeForWeb: pulumi.Output<number>;
    /**
     * URL from which to retrieve JWKs for this resource server. Used for verifying the JWT sent to Auth0 for token introspection.
     */
    declare public readonly verificationLocation: pulumi.Output<string | undefined>;

    /**
     * Create a ResourceServer resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ResourceServerArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: ResourceServerArgs | ResourceServerState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as ResourceServerState | undefined;
            resourceInputs["allowOfflineAccess"] = state?.allowOfflineAccess;
            resourceInputs["authorizationDetails"] = state?.authorizationDetails;
            resourceInputs["clientId"] = state?.clientId;
            resourceInputs["consentPolicy"] = state?.consentPolicy;
            resourceInputs["enforcePolicies"] = state?.enforcePolicies;
            resourceInputs["identifier"] = state?.identifier;
            resourceInputs["isSystem"] = state?.isSystem;
            resourceInputs["name"] = state?.name;
            resourceInputs["proofOfPossession"] = state?.proofOfPossession;
            resourceInputs["signingAlg"] = state?.signingAlg;
            resourceInputs["signingSecret"] = state?.signingSecret;
            resourceInputs["skipConsentForVerifiableFirstPartyClients"] = state?.skipConsentForVerifiableFirstPartyClients;
            resourceInputs["subjectTypeAuthorization"] = state?.subjectTypeAuthorization;
            resourceInputs["tokenDialect"] = state?.tokenDialect;
            resourceInputs["tokenEncryption"] = state?.tokenEncryption;
            resourceInputs["tokenLifetime"] = state?.tokenLifetime;
            resourceInputs["tokenLifetimeForWeb"] = state?.tokenLifetimeForWeb;
            resourceInputs["verificationLocation"] = state?.verificationLocation;
        } else {
            const args = argsOrState as ResourceServerArgs | undefined;
            if (args?.identifier === undefined && !opts.urn) {
                throw new Error("Missing required property 'identifier'");
            }
            resourceInputs["allowOfflineAccess"] = args?.allowOfflineAccess;
            resourceInputs["authorizationDetails"] = args?.authorizationDetails;
            resourceInputs["consentPolicy"] = args?.consentPolicy;
            resourceInputs["enforcePolicies"] = args?.enforcePolicies;
            resourceInputs["identifier"] = args?.identifier;
            resourceInputs["name"] = args?.name;
            resourceInputs["proofOfPossession"] = args?.proofOfPossession;
            resourceInputs["signingAlg"] = args?.signingAlg;
            resourceInputs["signingSecret"] = args?.signingSecret;
            resourceInputs["skipConsentForVerifiableFirstPartyClients"] = args?.skipConsentForVerifiableFirstPartyClients;
            resourceInputs["subjectTypeAuthorization"] = args?.subjectTypeAuthorization;
            resourceInputs["tokenDialect"] = args?.tokenDialect;
            resourceInputs["tokenEncryption"] = args?.tokenEncryption;
            resourceInputs["tokenLifetime"] = args?.tokenLifetime;
            resourceInputs["tokenLifetimeForWeb"] = args?.tokenLifetimeForWeb;
            resourceInputs["verificationLocation"] = args?.verificationLocation;
            resourceInputs["clientId"] = undefined /*out*/;
            resourceInputs["isSystem"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(ResourceServer.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering ResourceServer resources.
 */
export interface ResourceServerState {
    /**
     * Indicates whether refresh tokens can be issued for this resource server.
     */
    allowOfflineAccess?: pulumi.Input<boolean>;
    /**
     * Authorization details for this resource server.
     */
    authorizationDetails?: pulumi.Input<pulumi.Input<inputs.ResourceServerAuthorizationDetail>[]>;
    /**
     * The ID of the client associated with this resource server. If a client has been created and linked to this resource server, this field will be populated with that client's ID.
     */
    clientId?: pulumi.Input<string>;
    /**
     * Consent policy for this resource server. Options include `transactional-authorization-with-mfa`, or `null` to disable.
     */
    consentPolicy?: pulumi.Input<string>;
    /**
     * If this setting is enabled, RBAC authorization policies will be enforced for this API. Role and permission assignments will be evaluated during the login transaction.
     */
    enforcePolicies?: pulumi.Input<boolean>;
    /**
     * Unique identifier for the resource server. Used as the audience parameter for authorization calls. Cannot be changed once set.
     */
    identifier?: pulumi.Input<string>;
    /**
     * Indicates whether this resource server is a special resource server created by Auth0. It cannot be modified or deleted directly.
     */
    isSystem?: pulumi.Input<boolean>;
    /**
     * Friendly name for the resource server. Cannot include `<` or `>` characters.
     */
    name?: pulumi.Input<string>;
    /**
     * Configuration settings for proof-of-possession for this resource server.
     */
    proofOfPossession?: pulumi.Input<inputs.ResourceServerProofOfPossession>;
    /**
     * Algorithm used to sign JWTs. Options include `HS256`, `RS256`, and `PS256`.
     */
    signingAlg?: pulumi.Input<string>;
    /**
     * Secret used to sign tokens when using symmetric algorithms (HS256).
     */
    signingSecret?: pulumi.Input<string>;
    /**
     * Indicates whether to skip user consent for applications flagged as first party.
     */
    skipConsentForVerifiableFirstPartyClients?: pulumi.Input<boolean>;
    /**
     * Authorization policies for user and client flows.
     */
    subjectTypeAuthorization?: pulumi.Input<inputs.ResourceServerSubjectTypeAuthorization>;
    /**
     * Dialect of access tokens that should be issued for this resource server. Options include `accessToken`, `rfc9068Profile`, `accessTokenAuthz`, and `rfc9068ProfileAuthz`. `accessToken` is a JWT containing standard Auth0 claims. `rfc9068Profile` is a JWT conforming to the IETF JWT Access Token Profile. `accessTokenAuthz` is a JWT containing standard Auth0 claims, including RBAC permissions claims. `rfc9068ProfileAuthz` is a JWT conforming to the IETF JWT Access Token Profile, including RBAC permissions claims. RBAC permissions claims are available if RBAC (`enforcePolicies`) is enabled for this API. For more details, refer to [Access Token Profiles](https://auth0.com/docs/secure/tokens/access-tokens/access-token-profiles).
     */
    tokenDialect?: pulumi.Input<string>;
    /**
     * Configuration for JSON Web Encryption(JWE) of tokens for this resource server.
     */
    tokenEncryption?: pulumi.Input<inputs.ResourceServerTokenEncryption>;
    /**
     * Number of seconds during which access tokens issued for this resource server from the token endpoint remain valid.
     */
    tokenLifetime?: pulumi.Input<number>;
    /**
     * Number of seconds during which access tokens issued for this resource server via implicit or hybrid flows remain valid. Cannot be greater than the `tokenLifetime` value.
     */
    tokenLifetimeForWeb?: pulumi.Input<number>;
    /**
     * URL from which to retrieve JWKs for this resource server. Used for verifying the JWT sent to Auth0 for token introspection.
     */
    verificationLocation?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a ResourceServer resource.
 */
export interface ResourceServerArgs {
    /**
     * Indicates whether refresh tokens can be issued for this resource server.
     */
    allowOfflineAccess?: pulumi.Input<boolean>;
    /**
     * Authorization details for this resource server.
     */
    authorizationDetails?: pulumi.Input<pulumi.Input<inputs.ResourceServerAuthorizationDetail>[]>;
    /**
     * Consent policy for this resource server. Options include `transactional-authorization-with-mfa`, or `null` to disable.
     */
    consentPolicy?: pulumi.Input<string>;
    /**
     * If this setting is enabled, RBAC authorization policies will be enforced for this API. Role and permission assignments will be evaluated during the login transaction.
     */
    enforcePolicies?: pulumi.Input<boolean>;
    /**
     * Unique identifier for the resource server. Used as the audience parameter for authorization calls. Cannot be changed once set.
     */
    identifier: pulumi.Input<string>;
    /**
     * Friendly name for the resource server. Cannot include `<` or `>` characters.
     */
    name?: pulumi.Input<string>;
    /**
     * Configuration settings for proof-of-possession for this resource server.
     */
    proofOfPossession?: pulumi.Input<inputs.ResourceServerProofOfPossession>;
    /**
     * Algorithm used to sign JWTs. Options include `HS256`, `RS256`, and `PS256`.
     */
    signingAlg?: pulumi.Input<string>;
    /**
     * Secret used to sign tokens when using symmetric algorithms (HS256).
     */
    signingSecret?: pulumi.Input<string>;
    /**
     * Indicates whether to skip user consent for applications flagged as first party.
     */
    skipConsentForVerifiableFirstPartyClients?: pulumi.Input<boolean>;
    /**
     * Authorization policies for user and client flows.
     */
    subjectTypeAuthorization?: pulumi.Input<inputs.ResourceServerSubjectTypeAuthorization>;
    /**
     * Dialect of access tokens that should be issued for this resource server. Options include `accessToken`, `rfc9068Profile`, `accessTokenAuthz`, and `rfc9068ProfileAuthz`. `accessToken` is a JWT containing standard Auth0 claims. `rfc9068Profile` is a JWT conforming to the IETF JWT Access Token Profile. `accessTokenAuthz` is a JWT containing standard Auth0 claims, including RBAC permissions claims. `rfc9068ProfileAuthz` is a JWT conforming to the IETF JWT Access Token Profile, including RBAC permissions claims. RBAC permissions claims are available if RBAC (`enforcePolicies`) is enabled for this API. For more details, refer to [Access Token Profiles](https://auth0.com/docs/secure/tokens/access-tokens/access-token-profiles).
     */
    tokenDialect?: pulumi.Input<string>;
    /**
     * Configuration for JSON Web Encryption(JWE) of tokens for this resource server.
     */
    tokenEncryption?: pulumi.Input<inputs.ResourceServerTokenEncryption>;
    /**
     * Number of seconds during which access tokens issued for this resource server from the token endpoint remain valid.
     */
    tokenLifetime?: pulumi.Input<number>;
    /**
     * Number of seconds during which access tokens issued for this resource server via implicit or hybrid flows remain valid. Cannot be greater than the `tokenLifetime` value.
     */
    tokenLifetimeForWeb?: pulumi.Input<number>;
    /**
     * URL from which to retrieve JWKs for this resource server. Used for verifying the JWT sent to Auth0 for token introspection.
     */
    verificationLocation?: pulumi.Input<string>;
}
